### ISSUE TITLE
输出内容太混乱，提个建议

### ISSUE THREAD

**Issue by dahai0401** [fscarmen/sing-box#1]
建议再安装的时候加个交互选项，我用的客户端 
1.V2rayN 2.Shadowrocket 3.Clash Meta 4.NekoBox 5.All
如果用户选择5其实和以前一样，但是建议每个软件输出内容用不同颜色区分，这样直观一点。

**Comment by fscarmen** [comment]
> 建议再安装的时候加个交互选项，我用的客户端 1.V2rayN 2.Shadowrocket 3.Clash Meta 4.NekoBox 5.All 如果用户选择5其实和以前一样，但是建议每个软件输出内容用不同颜色区分，这样直观一点。

好建议，我稍后处理一下。

**Comment by fscarmen** [comment]
<img width="1265" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/80ec24b0-e52c-4e42-b315-55827e304303">

**Comment by dahai0401** [comment]
多谢采纳！
