### ISSUE TITLE
有没有可能一键全自动安装？

### ISSUE THREAD

**Issue by photkey** [fscarmen/sing-box#10]
所有选项 都在启动时 用参数传递, 这样保存一条命令 每次一键安装更爽呀。

**Comment by fscarmen** [comment]
有这样的计划，像 [ArgoX](https://github.com/fscarmen/ArgoX) 一样，设置好 config ，把需要用到的参数放进去，最后运行以下安装。但要等项目稳定了再说，现在还处于功能增加的阶段。
```
bash sing-box.sh -f < config file >
```

**Comment by fscarmen** [comment]
在现在的快捷键基础上加上去，再处理一下逻辑可以了，先稳定跑一下先，今天才更新了。

**Comment by fscarmen** [comment]
2024-3-27 v1.1.11 已经更新，支持两个方式的无交互快速安装
