### ISSUE TITLE
能否给reality加上vision流控

### ISSUE THREAD

**Issue by ouokj** [fscarmen/sing-box#101]

**Comment by fscarmen** [comment]
原来有的，但后面加了多路 h2mux + padding ，故只能把流控去掉，如果你要用 vision，即把服务端配置文件里的多路去掉，流控加上，重置 sing-box 就好了。

**Comment by ouokj** [comment]
> 原来有的，但后面加了多路 h2mux + padding ，故只能把流控去掉，如果你要用 vision，即把服务端配置文件里的多路去掉，流控加上，重置 sing-box 就好了。

好的，谢谢

**Comment by fscarmen** [comment]
在这个 commit 去掉 xtls-rprx-vision，你可以参照之前的写法
https://github.com/fscarmen/sing-box/commit/c984e522d2bec3108894e75d93f5117206c5733c
![image](https://github.com/fscarmen/sing-box/assets/62703343/782dffb1-ec21-4d38-b0cf-8e977e6fdced)

**Comment by x-socks** [comment]
建议给个选项会不会比较好点，或者加个参数

**Comment by fscarmen** [comment]
不想再增加交互啊，有几处地方要改
1、最常用的菜单模式 - 当用户选择 reality 的 3 个方式，要增加1步询问用户选择 vison 流控还是多路复用。
2、快捷无交互安装模式 - 传参或者配置方式式安装，都需要多添加一个变量，指明用什么方式，这个倒没有什么。
3、vison 和多路复用之间的来回切换。相信我，只要增加了选择功能，用户一定也要求切换功能的。就像我做隧道的转换、协议的增减这些动态变化。
4、输出节点信息和订阅信息的跟着变化

上面的那些都是花时间慢慢处理而已，难度不大。

我考虑最大的顾虑是：估计只有不到1成的少数用户有这个需求。其余超过9成的大多数用户，不会去作选择，但他们却要为这个交互而影响了用户体验。（我的理解是使用脚本的用户与手搓的大神不一样，他们希望交互越少越好，因为我就是这样的用户）

**Comment by x-socks** [comment]
> 快捷无交互安装模式 - 传参或者配置方式式安装，都需要多添加一个变量，指明用什么方式，这个倒没有什么。

传参应该是个好办法。因为vision跟多路复用好像目的不一样？vision是伪装性而多路复用是为了速度？总是有目的不同的用户
