### ISSUE TITLE
singbox脚本中reality协议的疑问

### ISSUE THREAD

**Issue by cn911007** [fscarmen/sing-box#102]
singbox脚本中添加的reality协议好像没有打开流控(flow)选项，同一台VPS中，速度明显比argx脚本中添加的reality协议打开流控(flow)选项情况的速度要低很多，而且神奇的是两个脚本生成出来的节点在打开油管网站的时候，识别为两个截然不同的地区。

**Comment by fscarmen** [comment]
> singbox脚本中添加的reality协议好像没有打开流控(flow)选项，同一台VPS中，速度明显比argx脚本中添加的reality协议打开流控(flow)选项情况的速度要低很多

https://github.com/fscarmen/sing-box/issues/101

> 而且神奇的是两个脚本生成出来的节点在打开油管网站的时候，识别为两个截然不同的地区

不应该这样，都是直连的。你再等长时间一点，打开 youtube 看看。

**Comment by cn911007** [comment]
SSH信息我已经发送到你邮箱了，大佬有时间可以看下我反馈的这两个问题，真的蛮神奇，我测试了好久都是这样的结果。

**Comment by fscarmen** [comment]
你可以先手动同时建3个节点，1. xray + reality-vison / 2. sing-box + reality-vison / 3. sing-box + multiplex + padding，使用不同的端口测试的一下
我这里的网络不快，可能测试的效果不佳，你可以试试

**Comment by fscarmen** [comment]
全部对比过了吗？效果如何？

**Comment by cn911007** [comment]
昨天晚高峰我新建了这两个节点做了速度对比：
1. xray + reality-vison ：速度峰值明显很高，但是不持久，高的时候油管27W，低的时候3W，速度时高时低
2. sing-box + reality-vison：速度峰值不高，但是速度比较稳定，一直持续在15W左右波动
3. sing-box + multiplex + padding：这个我不知道是什么协议，没有做测试对比。
1和2新建出来的节点还是会导致打开油管和谷歌的IP位置不同，xray是GB，sb是HK
