### ISSUE TITLE
功能建议：能否增加切换sing-box 内核版本功能，这样就可以在新版本有问题时切回到以前稳定的版本

### ISSUE THREAD

**Issue by ainp** [fscarmen/sing-box#103]
功能建议：能否增加切换sing-box 内核版本功能，这样就可以在新版本有问题时切回到以前稳定的版本，当然需要切换回以前相对应的配置功能

**Comment by fscarmen** [comment]
sing-box 升级太快了，而且旧配置不一定能用。按你的提议，需要维护两套配置，工作量很大，能力和时间有效，所以只能跟进最新的了。

**Comment by fscarmen** [comment]
我试了一下可以哦。
至于 `sb script`，请问这个具体指什么？
<img width="939" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/f7eefaf1-9a79-4487-bb85-84bfeee276f7">
<img width="966" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/a6931d38-e27f-4bb2-8323-ae3370ff3a98">

**Comment by fscarmen** [comment]
local VERSION_LATEST=
为空应该是当时通过github api查不成功，有可能是接口不稳定导致的，这样的情况多吗？如果多我有个异步的方法

**Comment by fscarmen** [comment]
> Sing-box 本地版本: 1.9.0-rc.18 最新版本: 不需要升级
> 
> 最新的版本是1.9.3，但检查不到。(已重新下载sb，另外建议sb也加入sb script的更新项目)

当前最新版本是 1.10.0-alpha.13 ，我已经更新脚本了。

<img width="948" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/2a4bea28-e7c2-426d-8dfc-e9a4a690405f">
