### ISSUE TITLE
输入快捷命令sb后出错

### ISSUE THREAD

**Issue by vincent975** [fscarmen/sing-box#105]
/dev/fd/63: line 905:  5221 Killed                  ${PACKAGE_UPDATE[int]} > /dev/null 2>&1

输入快捷命令sb后，出现以上提示，请问怎么解决？

**Comment by vincent975** [comment]
> /dev/fd/63: line 905: 5221 Killed ${PACKAGE_UPDATE[int]} > /dev/null 2>&1
> 
> 输入快捷命令sb后，出现以上提示，请问怎么解决？

**Comment by fscarmen** [comment]
什么情况？
