### ISSUE TITLE
希望增加一个修改配置的选项

### ISSUE THREAD

**Issue by suvonyang** [fscarmen/sing-box#107]
很好用的脚本，但是配置建好后无法修改，希望能增加这个选项。

**Comment by fscarmen** [comment]
谢谢支持。每个协议只有一个固定配置 json ，脚本里写好的。如果要改，只能手动改，同时不支持多添加变量的，比如 hysteria2 的 obfs 等。
如果是新增或者删除整个协议，脚本是支持的。

**Comment by suvonyang** [comment]
明白你这样设置的用意，简单可用。有一些是变量是可以增加修改选项而又不会影响可用性，例如ss更改加密方式，reality更改目标网站。

**Comment by kadidala** [comment]
希望能添加一个一键更换uuid的选项 🥇 
因为节点容易泄露，这样可以随时更换 🛩️

**Comment by fscarmen** [comment]
> 希望能添加一个一键更换uuid的选项 🥇 因为节点容易泄露，这样可以随时更换 🛩️

节点泄露你应该从源头找找什么问题，这个需求我觉得需求不大，所以暂时先不加了。如果你也挺频繁更换 uuid ，可以使用无交互极速安装 https://github.com/fscarmen/sing-box/blob/main/README.md#4%E6%97%A0%E4%BA%A4%E4%BA%92%E6%9E%81%E9%80%9F%E5%AE%89%E8%A3%85

先卸载，再改一下 uuid 安装，也不会太麻烦
