### ISSUE TITLE
vmess 和 vless 节点搭建好 没报错 但死活连不通

### ISSUE THREAD

**Issue by kadidala** [fscarmen/sing-box#109]
上个月搭建的一次就成功了，这两天搭建vmess 和 vless 死活连不通
域名用的eu.org解析的，origin rule 也设置正确了
有的时候 能ping通，但是没网，用优选ip也不行
求指点

**Comment by fscarmen** [comment]
试试 argo 回源

**Comment by kadidala** [comment]
> 试试 argo 回源

用Argo也试了，tunnel也设置了，还是连不通啊

**Comment by fscarmen** [comment]
多换换优选域名看看，再看看 cf 那里的域名设置有没有问题。

**Comment by syhacker** [comment]
嗯 我也是成功有点难啊 请问CF设置里SSL/TLS加密模式是灵活还是完全？？？？

**Comment by fscarmen** [comment]
> 嗯 我也是成功有点难啊 请问CF设置里SSL/TLS加密模式是灵活还是完全？？？？

我是设置为完全的

**Comment by codeworldai** [comment]
之前一直用argo token隧道回源，vless-ws-tls 与 vmess-ws都不通，换了argo临时隧道就通了
作者可以看一下是不是argo固定隧道部分的代码有bug

**Comment by fscarmen** [comment]
> 之前一直用argo token隧道回源，vless-ws-tls 与 vmess-ws都不通，换了argo临时隧道就通了 作者可以看一下是不是argo固定隧道部分的代码有bug

我复现不了呢，Token 隧道是正常的。

<img width="935" alt="image" src="https://github.com/user-attachments/assets/67731fc9-b20e-4a47-baa3-1c51bdd83045">
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/96d9bd1d-df6d-4a0f-8e16-e179eb3e91b8">
![image](https://github.com/user-attachments/assets/944b45e0-30d9-427c-8fe8-e934b39dd63e)

**Comment by codeworldai** [comment]
> > 之前一直用argo token隧道回源，vless-ws-tls 与 vmess-ws都不通，换了argo临时隧道就通了 作者可以看一下是不是argo固定隧道部分的代码有bug
> 
> 我复现不了呢，Token 隧道是正常的。
> 
> <img alt="image" width="935" src="https://private-user-images.githubusercontent.com/62703343/358452741-67731fc9-b20e-4a47-baa3-1c51bdd83045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzcxMDUsIm5iZiI6MTcyMzc3NjgwNSwicGF0aCI6Ii82MjcwMzM0My8zNTg0NTI3NDEtNjc3MzFmYzktYjIwZS00YTQ3LWJhYTMtMWM1MWJkZDgzMDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAyNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYmE0MDg5Y2I3YTBhMGNhOTNmNDEwNGEzNWFhNzc2NTVhYTk1MzE4NzJlYWQ3MmVjNTNkZjU3YmVkOGEyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WFZ4YoY_J7HPfnqBIeUR0Y2NJjNSEUXdUDHDwvRRcGc"> <img alt="image" width="1449" src="https://private-user-images.githubusercontent.com/62703343/358452829-96d9bd1d-df6d-4a0f-8e16-e179eb3e91b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzcxMDUsIm5iZiI6MTcyMzc3NjgwNSwicGF0aCI6Ii82MjcwMzM0My8zNTg0NTI4MjktOTZkOWJkMWQtZGY2ZC00YTBmLThlMTYtZTE3OWViM2U5MWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAyNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTliYWQyYTlkOWVmMjJkYTZhMjIyMzA4MzU0NWQ3ZWZiNTg1ZTc3YTEyNDBjNjNiZDhlMDYyMTJmN2I2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.34eTiUgK_eu-i389HqRzN86nOwLCuvvaNsgLbnIOJKg"> <img alt="image" width="1473" src="https://private-user-images.githubusercontent.com/62703343/358453378-af288af4-0063-46f9-8636-a9f06db091c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzcxMDUsIm5iZiI6MTcyMzc3NjgwNSwicGF0aCI6Ii82MjcwMzM0My8zNTg0NTMzNzgtYWYyODhhZjQtMDA2My00NmY5LTg2MzYtYTlmMDZkYjA5MWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAyNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMmUwZjYyZDAzM2JkZWVmODlmNGJhZGUxZjYzZDU4MzljOWM2ZTNiZjBmN2NmODllOGNiNThkYzg2YWMzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aji4iM4KlTXRIbbM3HMXLv11XneNfW9aI8a9Xt0-9gk">
那我知道了，可能是我的域名有问题
us.kg是不是也全国屏蔽了

**Comment by codeworldai** [comment]
看到你的域名，我感觉可能是我的域名有问题，us.kg是不是也全国屏蔽了

**Comment by fscarmen** [comment]
好像不是啊，us.kg应该可以吧，我试试

**Comment by fscarmen** [comment]
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/7a9b0383-1f6b-4bf8-bb49-ca7b37e5b05e">
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/b60255f9-6085-432c-9f3b-e73d7c7f573f">
<img width="1473" alt="image" src="https://github.com/user-attachments/assets/92ba0cec-06a2-444a-aa01-326e3fae5ed1">
<img width="1660" alt="image" src="https://github.com/user-attachments/assets/54e070cd-b9e9-4e6c-9745-9a90db90a5fc">

**Comment by codeworldai** [comment]
刚刚全试了一遍，除了临时隧道，不管是 Argo Token、Argo Json 还是 Origin rule，vless-ws-tls 和 vmess-ws 都不通。

**Comment by codeworldai** [comment]
> 刚刚全试了一遍，除了临时隧道，不管是 Argo Token、Argo Json 还是 Origin rule，vless-ws-tls 和 vmess-ws 都不通。

还好其他都通，看看其他人什么情况

**Comment by fscarmen** [comment]
> 刚刚全试了一遍，除了临时隧道，不管是 Argo Token、Argo Json 还是 Origin rule，vless-ws-tls 和 vmess-ws 都不通。

你换个优选域名看看。项目里有多个，你逐一试试，我觉得问题可能出在那里

**Comment by codeworldai** [comment]
> > 刚刚全试了一遍，除了临时隧道，不管是 Argo Token、Argo Json 还是 Origin rule，vless-ws-tls 和 vmess-ws 都不通。
> 
> 你换个优选域名看看。项目里有多个，你逐一试试，我觉得问题可能出在那里
宝塔迷里面的优选域名全试了，还是不行，不折腾了，其他的协议已经够用了；
另外不得不说这个脚本嘎嘎好用。

**Comment by codeworldai** [comment]
宝塔迷里面的优选域名全试了，还是不行，不折腾了，其他的协议已经够用了；
另外不得不说这个脚本嘎嘎好用。

**Comment by MaleicAcid** [comment]
遇到了相同的情况，感觉不是优选域名的问题

**Comment by li12138** [comment]
> > 嗯 我也是成功有点难啊 请问CF设置里SSL/TLS加密模式是灵活还是完全？？？？
> 
> 我是设置为完全的

改为完全,我终于也能用了

**Comment by lleeopen** [comment]
SNI阻断，用v2rayn客户端，开启tls分片，可以解决，或者用cf的优先ipv6地址

**Comment by fscarmen** [comment]
us.kg也有eu.org同等代遇吗？

**Comment by MaleicAcid** [comment]
![image](https://github.com/user-attachments/assets/9e7e754d-87da-4995-85e6-fb4e15f6fd1e)

![image](https://github.com/user-attachments/assets/0a779049-2fa8-4589-9bc3-8f15dbde1f5d)

> SNI阻断，用v2rayn客户端，开启tls分片，可以解决，或者用cf的优选ipv6地址

**Comment by li12138** [comment]
> us.kg也有eu.org同等待遇吗？
我用的us.kg，也是一样的，vless又是能测出延迟，但用不了，vmess直接连延迟都测不出来

**Comment by lleeopen** [comment]
Xray 支持 tls分片 ，vless trojan vmess都用 Xray，回源或者argo基本一样

**Comment by li12138** [comment]
我重装系统,使用Argo,域名skk.moe, vless+ws+tls能用了

**Comment by fscarmen** [comment]
就是优选域名不行，可用脚本推荐的5，6个试下

**Comment by li12138** [comment]
> 现在直接用固定ARGO隧道了，优选域名可以用 icook.hk

vless和vmess都能用吗?我用vless可以,但是vmess测延迟都失败

**Comment by fscarmen** [comment]
> vless和vmess都能用吗?我用vless可以,但是vmess测延迟都失败

是的，都可以的。

**Comment by li12138** [comment]
> > vless和vmess都能用吗?我用vless可以,但是vmess测延迟都失败
> 
> 是的，都可以的。
> 
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/62703343/363454259-e3cdf9ca-e1a1-40c0-a002-441db897446c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDE5ODIsIm5iZiI6MTcyNTIwMTY4MiwicGF0aCI6Ii82MjcwMzM0My8zNjM0NTQyNTktZTNjZGY5Y2EtZTFhMS00MGMwLWEwMDItNDQxZGI4OTc0NDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE0NDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODQwMjY0NmRiMjcwODBjNDk0YjlkMTQ5NDVjNDI4NjY0NjI3YjU2NzY5YTg1NDM0ZDRkMzEwZTAwMDQ4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9xtZbjMBTnxTt0yZYieYJD3HiFqvQdeKh6G3pKIDh4Q">

你这是ipv6节点吗?我用的ipv4,试了好多次,vless能成功,但是vmess就是失败

**Comment by fscarmen** [comment]
ipv4

<img width="848" alt="image" src="https://github.com/user-attachments/assets/c5aef1cf-861f-47a3-9a0f-808edd4c8767">

**Comment by li12138** [comment]
> ipv4
> 
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/62703343/363505328-c5aef1cf-861f-47a3-9a0f-808edd4c8767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDc2MTksIm5iZiI6MTcyNTI0NzMxOSwicGF0aCI6Ii82MjcwMzM0My8zNjM1MDUzMjgtYzVhZWYxY2YtODYxZi00N2EzLTlhMGYtODA4ZWRkNGM4NzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAzMjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZTA0MWNiODc2ODgyYWNkMTZiMjUxMTQyNjU1ZWRiNzAxNTFmZmI3NDk0MDZjYzFlMTNhN2ZlY2I4YWFhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nj9arXke5uLiPqqV8hkda_TKQ7UqAJkUWI49ub6p_dM">

有没有可能是因为脚本的vmess没有tls导致的？
我用了另一个脚本 https://github.com/eooce/xray-2go ，这个的vmess+ws+tls，使用argo固定隧道，优选域名是www.visa.com.tw,能测延迟成功

**Comment by fscarmen** [comment]
你试试 使用 vps-jdkz.tk ，端口设置为 80，不知道是不是你使用的优选不支持非 ssl ，域名ssl设置为完全看看

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/31552bf4-b61c-401f-86e2-75f267c3d874">

**Comment by li12138** [comment]
> 你试试 使用 vps-jdkz.tk ，端口设置为 80，不知道是不是你使用的优选不支持非 ssl ，域名ssl设置为完全看看
> 
> <img alt="image" width="1333" src="https://private-user-images.githubusercontent.com/62703343/363576682-31552bf4-b61c-401f-86e2-75f267c3d874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjgzNjcsIm5iZiI6MTcyNTI2ODA2NywicGF0aCI6Ii82MjcwMzM0My8zNjM1NzY2ODItMzE1NTJiZjQtYjYxYy00MDFmLTg2ZTItNzVmMjY3YzNkODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWZiZGQyOTkxYjc3NjdhZDE1M2Q1MzlmNjIzYzU0ZTIyN2VkNTBjZGU5YzAxYTJjYzExOWY2ZGVhMDc0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-RCY5vy9epR8wuvTZiycDRaKKJqBHooI82Rhjv-r9s">

做了，
依然不行，在loon，小火箭和gui for clash都用不了，
另外那个脚本的vmess在loon和小火箭能用，但是在gui for clash用不了，

**Comment by fscarmen** [comment]
看其他网友也没有这个反馈，同时我也复现不了，我也不知道如何解决了。
