### ISSUE TITLE
Hysteria2, TUIC, 回原的vmess和vless 都无法运行

### ISSUE THREAD

**Issue by Doutianbao** [fscarmen/sing-box#11]
如题，
一键安装了所有协议

之前Hysteria2能用，很快

**Comment by fscarmen** [comment]
Hysteria2, TUIC是udp的，问一下是否限制了。
ws的回源对着说明看看有没漏。

**Comment by Doutianbao** [comment]
谢谢提醒。
小白把udp端口打开，目前hy2和tuic正常运行

回源端口设置那里有疑问:先跑脚本，结果显示端口数再去设置CF
还是先设置CF那里？

**Comment by Doutianbao** [comment]
还有如何更换优选IP，除了卸载重新安装

**Comment by Doutianbao** [comment]
非常感谢，hy2和tuic可以使用了

但是回源的还是不行，设置是按图片步骤进行的。如果who那个IP不行，我该选哪一个以及如何更换。icook.tw似乎也打不开

**Comment by fscarmen** [comment]
你再查查端口有没有设置错呢，脚本安装好，会有提示参数的，至于为什么不行，查查你的ssl是不是设置为完全，暂时想不到原因。

**Comment by Doutianbao** [comment]
> 你再查查端口有没有设置错呢，脚本安装好，会有提示参数的，至于为什么不行，查查你的ssl是不是设置为完全，暂时想不到原因。

version 7有问题- -

**Comment by fscarmen** [comment]
有什么问题，如何复现？

**Comment by Doutianbao** [comment]
能安装协议，但是所有的链接都没法使用。我是手动选择的bcdefg,

我看了一下代码的变更，过于复杂。  自己手动存一份version 6的代码养老吧

**Comment by fscarmen** [comment]
有点小bug，已经重新更新了。

**Comment by silentxrture** [comment]
> 有点小bug，已经重新更新了。

你好大佬，首先感谢你的脚本，非常好用！然后我目前遇到一个问题不知道你能否提供解决思路。我现在手上一台搬瓦工cn2gia和一台akile香港机，通过你的脚本并且两边同样的配置，搬瓦工能够正常使用hy2和tuic，但另一台机器上测试了hy2,tuic,vmess优选ip.vless优选ip都是无法正常使用的，我尝试通过防火墙命令放行了udp端口后还是无法解决，请问大佬这有可能是哪里出了问题呢？

**Comment by fscarmen** [comment]
> 但另一台机器上测试了hy2,tuic,vmess优选ip.vless优选ip都是无法正常使用的

看看服务有没有起来。 `ss -nltp` 看看，没有什么好头绪。

**Comment by silentxrture** [comment]
> > 但另一台机器上测试了hy2,tuic,vmess优选ip.vless优选ip都是无法正常使用的
> 
> 看看服务有没有起来。 `ss -nltp` 看看，没有什么好头绪。

sing-box 服务正常运行，且reality, trojan, shadowtls. ss都能正常代理，我使用 `ss -nltp` 这个命令输出如图所示，好像hy2的端口没有被正常启用（我hy2的端口是6700）
![image](https://github.com/fscarmen/sing-box/assets/54028126/5b22d037-314a-4a9b-bd23-073d5ca586aa)

**Comment by fscarmen** [comment]
> > > 但另一台机器上测试了hy2,tuic,vmess优选ip.vless优选ip都是无法正常使用的
> > 
> > 
> > 看看服务有没有起来。 `ss -nltp` 看看，没有什么好头绪。
> 
> sing-box 服务正常运行，且reality, trojan, shadowtls. ss都能正常代理，我使用 `ss -nltp` 这个命令输出如图所示，好像hy2的端口没有被正常启用（我hy2的端口是6700） ![image](https://user-images.githubusercontent.com/54028126/278657442-5b22d037-314a-4a9b-bd23-073d5ca586aa.png) 重启，重装，设置不同端口等方法我都试过了
> 
> edit: 目前发现应该是机房限制了udp，大佬不必回复了，再次感谢分享这么好用的脚本

你的命令只能查 tcp 端口，改为 `ss -nlutp` 一并查 udp的。

**Comment by silentxrture** [comment]
> > > > 但另一台机器上测试了hy2,tuic,vmess优选ip.vless优选ip都是无法正常使用的
> > > 
> > > 
> > > 看看服务有没有起来。 `ss -nltp` 看看，没有什么好头绪。
> > 
> > 
> > sing-box 服务正常运行，且reality, trojan, shadowtls. ss都能正常代理，我使用 `ss -nltp` 这个命令输出如图所示，好像hy2的端口没有被正常启用（我hy2的端口是6700） ![image](https://user-images.githubusercontent.com/54028126/278657442-5b22d037-314a-4a9b-bd23-073d5ca586aa.png) 重启，重装，设置不同端口等方法我都试过了
> > edit: 目前发现应该是机房限制了udp，大佬不必回复了，再次感谢分享这么好用的脚本
> 
> 你的命令只能查 tcp 端口，改为 `ss -nlutp` 一并查 udp的。

![image](https://github.com/fscarmen/sing-box/assets/54028126/dfc17e55-39cf-422e-a812-d6ea650a2d6a)
