### ISSUE TITLE
使用软路由的openclash订阅失败，提示错误，请见图片。

### ISSUE THREAD

**Issue by QZQ-QSQ** [fscarmen/sing-box#111]
使用软路由的openclash订阅clash或clash2，都失败，提示错误，请见图片。需要使用第三方订阅转换后，才能使用。但不想转，担心泄露。
提示错误的行列地方，是图4圈起的那里。
![A](https://github.com/user-attachments/assets/c69a04b2-7fc6-4b4f-a8f5-d63a05f2fef2)
![B](https://github.com/user-attachments/assets/7acd2ea0-0718-4772-bce3-fca2b2f899fd)
![1](https://github.com/user-attachments/assets/ac5617c0-4ee8-40ff-a9ec-2bcb027624df)
![2](https://github.com/user-attachments/assets/bf643391-1514-4f12-9b4f-0695e3321140)

**Comment by fscarmen** [comment]
麻烦你手动改一下订阅文件，路径是 /etc/sing-box/subscribe/proxies，把那个 `flow:,` 去掉 ，保存，马上使用订阅看看

**Comment by QZQ-QSQ** [comment]
> 麻烦你手动改一下订阅文件，路径是 /etc/sing-box/subscribe/proxies，把那个 `flow:,` 去掉 ，保存，马上使用订阅看看
你好，只修改proxies的还是不行，需要同时修改clash2的，这样就可以。另外clash（不带数字的）也是不能订阅。
