### ISSUE TITLE
生成的 sing-box 订阅文件中 vmess-ws 节点重复出现

### ISSUE THREAD

**Issue by codeworldai** [fscarmen/sing-box#113]
生成的 Sing-box 订阅文件如下：  
      "outbounds": [
        "DIRECT",
        "♻️ 自动选择",
        "sing-box xtls-reality",
        "sing-box hysteria2",
        "sing-box tuic",
        "sing-box ShadowTLS",
        "sing-box shadowsocks",
        "sing-box trojan",
        "sing-box vmess-ws",
        "sing-box vmess-ws",
        "sing-box vless-ws-tls",
        "sing-box h2-reality",
        "sing-box grpc-reality"
      ]
看完代码后发现是在脚本第2318行多了一句节点名称的追加操作
 && local NODE_REPLACE+="\"${NODE_NAME[17]} ${NODE_TAG[6]}\","

**Comment by fscarmen** [comment]
收到，谢谢反馈，下次更新时一并处理。

**Comment by fscarmen** [comment]
已更新了，感谢反馈，而且还是直接定点到bug的地方，谢谢！
