### ISSUE TITLE
docker容器重启就会初始化，怎么固化一些配置呢？

### ISSUE THREAD

**Issue by hzdlive** [fscarmen/sing-box#115]
docker容器重启就会初始化，怎么固化一些配置呢？

**Comment by hzdlive** [comment]
比如我的Vps在香港，但chatgpt的一些网站又限制地区，所以想添加一些路由规则，这个该怎么操作呢?

**Comment by fscarmen** [comment]
> docker容器重启就会初始化，怎么固化一些配置呢？

容器重启的话，因为环境变量没有变，所以还是你初始部署时的参数，所以我也没有设计用 -v 来映射到宿主机的文件夹

> 比如我的Vps在香港，但gemini，anthropic等一些网站又限制地区，所以想添加一些路由规则，这个该怎么操作呢?

这个建议你本地使用更专业的客户端，像 clash , v2rayN 这样来分流，让服务端的节点保护不变。
