### ISSUE TITLE
自带的warp的密钥不能更改吗？

### ISSUE THREAD

**Issue by li12138** [fscarmen/sing-box#117]
我改成我自己以前用的warp密钥，就加载不出来网页，
我手机上用代理链trojan-warp能用的，说明该密钥没问题啊，但是换上去就不行

**Comment by fscarmen** [comment]
改了换密钥，还要换v6和serverd

**Comment by fscarmen** [comment]
记得重启一下 sing-box

**Comment by fscarmen** [comment]
官方问题，过一两天自动恢复了，我刚才试已经可以了。
