### ISSUE TITLE
请问怎样设置端口转发?

### ISSUE THREAD

**Issue by li12138** [fscarmen/sing-box#122]
https://lala.im/9147.html

我看这个教程讲sing-box可以端口转发,但是我稍做一点改动,sing-box就无法启动了,如果想实现这种端口转发,该怎么设置?

**Comment by li12138** [comment]
最好是可以分协议端口转发,比如hy2端口转发,trojan不转发

**Comment by fscarmen** [comment]
我也不懂，你可以试试233boy的脚本
https://233boy.com/sing-box/sing-box-direct/

https://github.com/233boy/sing-box

**Comment by solanab** [comment]
> sing-box的direct功能就是相当于xray的Dokodemo door（任意门），即port forward功能
> 
> https://sing-box.sagernet.org/configuration/inbound/direct/
> 
> 
> 
> 中文视频讲解请参考下面连接
> 
> https://www.youtube.com/watch?v=rYRAX-NctIw
> 
> 
> 
>  

 _Originally posted by @egg1234 in [#743](https://github.com/SagerNet/sing-box/issues/743#issuecomment-1658993217)_

**Comment by fscarmen** [comment]
端口转发，不是用内核态的 ipt 比 用户太的 sing-box 要强吗？
