### ISSUE TITLE
clash meta的东西怎么用啊

### ISSUE THREAD

**Issue by allen0826** [fscarmen/sing-box#123]
就导出来一长串东西  和clash meta格式不一样  不方便导入

**Comment by fscarmen** [comment]
你指哪里与clash meta 格式不一样？

**Comment by allen0826** [comment]
就是导入到clash vega客户端用不了

**Comment by fscarmen** [comment]
订阅那里不行吗？

allen0826 ***@***.***> 于2024年9月14日周六 22:15写道：

**Comment by allen0826** [comment]
订阅会报错  那个singbox也不行  试过很多次 配置导进去无法启动singbox 弹出那个127.0.0.1:9090是打不开的  换过别的singbox脚本导进去是可以启动的

**Comment by fscarmen** [comment]
具体我也不清楚问题出在哪里了，脚本运行后的速度应该差不多的，哪个能用，用着顺手就用哪个啦！
