### ISSUE TITLE
clash订阅信息生成有问题

### ISSUE THREAD

**Issue by gggssepgf** [fscarmen/sing-box#125]
只有在第一次执行完成安装后生成的订阅信息才是对的，如下图，
![e2b70be3854efa84658aaf8fc91cf512](https://github.com/user-attachments/assets/f478465b-ec43-486b-8357-cc5022eb942f)
只要再执行一次 sb -n，节点的订阅信息就会出问题，导致订阅失败，如下图
![6a15c2c6e316e8a3d2dcf655ed724529](https://github.com/user-attachments/assets/255b046d-2966-40aa-992f-499670cf04eb)
缺失了节点的名字

**Comment by fscarmen** [comment]
收到，这两天看看

**Comment by fscarmen** [comment]
> 收到，这两天看看

已处理，如果你重新安装的话，再按 -n 是没有问题的。但如果你现在已经安装，又不能订阅的话，请编辑 `/etc/sing-box/subscribe/clash` 在33行  `u: &u {use: ['']}`  这里的 '' 处加上你的节点名，在45行那里也要加一模一样的名称，如下图所示。
<img width="758" alt="image" src="https://github.com/user-attachments/assets/c3bec258-523f-4eb0-aafb-e4f525a9a9c8">

感谢大佬的支持和反馈，并快速帮我定点到问题。
