### ISSUE TITLE
添加amaozn规则集就无法启动了

### ISSUE THREAD

**Issue by li12138** [fscarmen/sing-box#126]
![2024-10-30_14-24](https://github.com/user-attachments/assets/123e4813-c083-446f-8c3d-54c1c8263c59)
只有domain-keyword这种的添加还能正常用，添加规则集就无法使用，

**Comment by li12138** [comment]
上面的规则集添加没写错吧，英文逗号也加了，
下面的两个rule-set我也试过写到两个{}里，用英文逗号隔开，传上去也是无法再打开singbox了

**Comment by fscarmen** [comment]
两个rule_set不能这样写的，要看看sb文档，要么用数组，要么需要分开对象

**Comment by li12138** [comment]
> 两个rule_set不能这样写的，要看看sb文档，要么用数组，要么需要分开对象

![image](https://github.com/user-attachments/assets/8062120a-2972-466b-9732-00fa2a71e19d)

这样是吧，我从网上的模板找到，模仿试过了，传上去也无法启动

**Comment by fscarmen** [comment]
先到json.cn查下json文件有没格式问题。再手动运行`/etc/sing-box/sing-box run -C /etc/sing-box/conf/` 看报什么错，问下ai。

**Comment by li12138** [comment]
> 先到json.cn查下json文件有没格式问题。再手动运行`/etc/sing-box/sing-box run -C /etc/sing-box/conf/` 看报什么错，问下ai。

多谢,搞定了,是链接不是raw原始文件URL的原因

**Comment by fscarmen3** [comment]
怪不得，意思就是那个 `geosite-amazon.srs` 地址有问题导致出错，我也没有看出来，是完全没有想到你那有问题，估计你手动运行时，日志会指出来，这样就容易判断了。

**Comment by fscarmen** [comment]
怪不得，意思就是那个 geosite-amazon.srs 地址有问题导致出错，我也没有看出来，是完全没有想到你那有问题，估计你手动运行时，日志会指出来，这样就容易判断了。
