### ISSUE TITLE
docker_init.sh的nginx出现小问题&&订阅和隧道进行双栈支持

### ISSUE THREAD

**Issue by abirvepete** [fscarmen/sing-box#128]
docker_init.sh nginx出现问题分别是
1.http2 写法更新
      listen 127.0.0.1:$START_PORT ssl http2; # sing-box backend
改成
      listen 127.0.0.1:$START_PORT ssl ; # sing-box backend
      http2 on;
2.代理端口有问题：

  [ "$**{VLESS_WS}**" = 'true' ] && NGINX_CONF+="
      # 反代 sing-box websocket
      location /${UUID}-vmess {
        if (\$http_upgrade != "websocket") {
           return 404;
        }
        proxy_pass                          http://127.0.0.1:**${PORT_VMESS_WS}**;

  [ "$**{VMESS_WS}**" = 'true' ] && NGINX_CONF+="
      # 反代 sing-box vless websocket
      location /${UUID}-vless {
        if (\$http_upgrade != "websocket") {
           return 404;
        }
        proxy_pass                          http://127.0.0.1:$**{PORT_VLESS_WS}**;

vmess的反代端口和vless的反代端口写反了
订阅和隧道双栈支持，argo隧道的双栈不知道怎么实现，自己改得不太行，希望这个可以实现

**Comment by fscarmen** [comment]
谢谢提配，你提到的argo双栈是指什么？

**Comment by abirvepete** [comment]
实践了一下，发现Argo同时识别ipv4和ipv6为主机是不是不太可能？

主要是订阅。脚本中的订阅服务很好，我同时使用IPv4和IPv6，希望增加一个IPv6选项，使订阅输出同时包含IPv4和IPv6两个版本。
