### ISSUE TITLE
再次麻烦大佬。warp解锁chatGPT 不能用了？

### ISSUE THREAD

**Issue by sw19999** [fscarmen/sing-box#139]
使用iOS客户端居多。上周还在用。

racketed的服务器，脚本检测是说解锁ChatGPT，实际上是不可以的。

/etc/sing-box/conf/02_route.json

            {
                "domain":"api.openai.com",
                "outbound":"direct"
            },
            {
                "rule_set":"geosite-openai",
                "outbound":"direct"
            }

修改成：

            {
                "domain":"api.openai.com",
                "outbound":"warp-IPv4-out"
            },
            {
                "rule_set":"geosite-openai",
                "outbound":"warp-IPv4-out"
            }

一直这么用的。最近也没有升级sing-box核心

**Comment by fscarmen** [comment]
你重装一下，之前的 warp endpoint 应该从上周末开始不能用了，我已经处理了。

**Comment by sw19999** [comment]
重装可以了。
