### ISSUE TITLE
无法使用链式代理

### ISSUE THREAD

**Issue by helloworld-men** [fscarmen/sing-box#14]
用这个脚本搭建的所有协议都无法使用链式代理，而我用其他脚本搭建的trojan-go可以使用

**Comment by fscarmen** [comment]
现在只设置了访问 chatGPT 使用 warp ，其他网没有的，如果你要设置，请处理 /etc/sing-box/conf/02_route.json，warp 的配置在  /etc/sing-box/conf/01_outbounds.json  里已经配置好了。谢谢！
