### ISSUE TITLE
新版sing-box内核对hysteria2出站协议添加了端口跳跃支持

### ISSUE THREAD

**Issue by Maxrxf** [fscarmen/sing-box#140]
[sing-box.sh](https://github.com/fscarmen/sing-box/blob/2415986d187127830ec84524e45a2e469cb93dc9/sing-box.sh#L2316)
可以修改为
`local INBOUND_REPLACE+=" { \"type\": \"hysteria2\", \"tag\": \"${NODE_NAME[12]} ${NODE_TAG[1]}\", \"server\": \"${SERVER_IP}\", \"server_port\": ${PORT_HYSTERIA2}, \"server_ports\": [ \"${PORT_HOPPING_START}:${PORT_HOPPING_END}\" \], \"up_mbps\": 200, \"down_mbps\": 1000, \"password\": \"${UUID[12]}\", \"tls\": { \"enabled\": true, \"insecure\": true, \"server_name\": \"\", \"alpn\": [ \"h3\" ] } }," &&`
以生成对应的参数

**Comment by fscarmen** [comment]
谢谢提醒，去sing-box主页看到 

1.11.0-beta.17
Add port hopping support for Hysteria2 1
Fixes and improvements
1:

See [Hysteria2](https://sing-box.sagernet.org/configuration/outbound/hysteria2/).

Structure
```
{
  "type": "hysteria2",
  "tag": "hy2-out",

  "server": "127.0.0.1",
  "server_port": 1080,
  "server_ports": [
    "2080:3000"
  ],
  "hop_interval": "",
  "up_mbps": 100,
  "down_mbps": 100,
  "obfs": {
    "type": "salamander",
    "password": "cry_me_a_r1ver"
  },
  "password": "goofy_ahh_password",
  "network": "tcp",
  "tls": {},
  "brutal_debug": false,

  ... // Dial Fields
}
```

这样的确方便了很多，今天更新一下。

**Comment by fscarmen** [comment]
有点失望了，还以为是服务端支持，不再需要根据系统使用 `iptables` 和 `firewall-cmd`。正在处理脚本里发现配置那里怪怪的，没有 `"listen":"::"`，原来只是出站支持，而极少极少用户使用 sing-box 作为客户端的。

**Comment by fscarmen** [comment]
已更新

**Comment by Maxrxf** [comment]
> 有点失望了，还以为是服务端支持，不再需要根据系统使用 `iptables` 和 `firewall-cmd`。正在处理脚本里发现配置那里怪怪的，没有 `"listen":"::"`，原来只是出站支持，而极少极少用户使用 sing-box 作为客户端的。

用sing-box 作为客户端的确实少
