### ISSUE TITLE
部分协议无法玩游戏?

### ISSUE THREAD

**Issue by MurasameCyan** [fscarmen/sing-box#16]
win11 nekobox 3.23 tun模式 测试游戏 星铁
 hy2  和 Reality  无法进入游戏  
tuic 和trojan 正常   

但是gcp用tuic很容易触发谷歌的风控 导致可能ban gcp  ...

这是什么问题?

**Comment by fscarmen** [comment]
试试客户端开 tun呢，由于我不玩游戏，所以解答不了你。
