### ISSUE TITLE
b7更新至v1  sb快捷方式无法使用  另外 考虑添加bbr v3吗?

### ISSUE THREAD

**Issue by MurasameCyan** [fscarmen/sing-box#17]
rt

**Comment by fscarmen** [comment]
重新安装才有的，或者你手动

```
WORK_DIR=/etc/sing-box
cat > $WORK_DIR/sb.sh << EOF
#!/usr/bin/env bash

bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) \$1
EOF
chmod +x $WORK_DIR/sb.sh
ln -sf $WORK_DIR/sb.sh /usr/bin/sb
```

**Comment by EluneAdore1** [comment]
没有所谓的bbr3 
https://github.com/google/bbr

**Comment by MurasameCyan** [comment]
> 没有所谓的bbr3 https://github.com/google/bbr

你在讲什么飞机?
![image](https://github.com/fscarmen/sing-box/assets/50967145/fe9a4537-3eeb-469a-80a9-15a162647c31)
![image](https://github.com/fscarmen/sing-box/assets/50967145/98fd31ad-6aa2-42ec-8c08-0a068139610d)

**Comment by EluneAdore1** [comment]
我眼瞎了，我认错。

**Comment by fscarmen** [comment]
不知道tcp brutal与bbr有没冲突？
