### ISSUE TITLE
求教，sing-box的配置文件怎么添加chatGPT和奈飞解锁？

### ISSUE THREAD

**Issue by kay-zhu** [fscarmen/sing-box#2]
"outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "rules": [
            {
                "geoip": "cn",
                "outbound": "block"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            }
        ],
        "final": "direct"
    }
}

**Comment by kay-zhu** [comment]
如下的这个，怎么添加上去？谢谢

{
    "outbounds":[
        {
            "protocol":"freedom",
            "tag": "direct"
        },
        {
            "protocol":"wireguard",
            "settings":{
                "secretKey":"YFYOAdbw1bKTHlNNi+aEjBM3BO7unuFC5rOkMRAz9XY=", // 粘贴你的 "private_key" 值
                "address":[
                    "172.16.0.2/32",
                    "2606:4700:110:8a36:df92:102a:9602:fa18/128"
                ],
                "peers":[
                    {
                        "publicKey":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "allowedIPs":[
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "endpoint":"engage.cloudflareclient.com:2408" // 或填写 162.159.193.10:2408 或 [2606:4700:d0::a29f:c001]:2408
                    }
                ],
                "reserved":[78, 135, 76], // 粘贴你的 "reserved" 值
                "mtu":1280
            },
            "tag":"wireguard"
        },
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            },
            "proxySettings":{
                "tag":"wireguard"
            },
            "tag":"warp-IPv4"
        },
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv6"
            },
            "proxySettings":{
                "tag":"wireguard"
            },
            "tag":"warp-IPv6"
        }
    ],
    "routing":{
        "domainStrategy":"AsIs",
        "rules":[
            {
                "type":"field",
                "domain":[
                    "geosite:openai",
                    "ip.gs"
                ],
                "outboundTag":"warp-IPv4"
            },
            {
                "type":"field",
                "domain":[
                    "geosite:netflix",
                    "p3terx.com"
                ],
                "outboundTag":"warp-IPv6"
            }
        ]
    }
}

**Comment by fscarmen** [comment]
请参照 /etc/sing-box/conf/02_route.json，其余自行处理
```
{
    "route":{
        "geoip":{
            "download_url":"https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
            "download_detour":"direct"
        },
        "geosite":{
            "download_url":"https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
            "download_detour":"direct"
        },
        "rules":[
            {
                "geosite":[
                    "openai"
                ],
                "outbound":"warp-IPv6-out"
            }
        ]
    }
}
```

**Comment by kay-zhu** [comment]
使用UDP的HY2和TUIC似乎不支持这种方式解锁？

**Comment by fscarmen** [comment]
> 使用UDP的HY2和TUIC似乎不支持这种方式解锁？

可以啊，我使用 hy2协议的时候，看chatGPT也是warp的ip

**Comment by alexallen1** [comment]
> 使用UDP的HY2和TUIC似乎不支持这种方式解锁？
下面能用的route范例，outbound 有个节点，tag为'unlock'
```
"route": {
    "rules": [

        {
            "outbound": "block",
            "geoip": [
                "private"
            ]
        },

        {
            "geosite": ["netflix","openai","dazn","hotstar","primevideo","hbo"],
            "outbound": "unlock"
        },
        {
            "geosite": ["disney","viu","mytvsuper","tvb","dazn"],
            "outbound": "unlock-hk"
        },
        {
            "geosite": [
                "google"
            ],
            "outbound": "direct"
        },
        {
            "geosite": [
                "cn"
            ],
            "outbound": "block"
        },
        {
            "geoip": [
                "cn"
            ],
            "outbound": "block"
        },

```

**Comment by fscarmen** [comment]
现在脚本会先行检测 vps 本身的 ip 是否解锁，如果解锁，就不使用 warp 了，如果不解锁，就使用内置好的 warp 。具体看 
/etc/sing-box/conf/02_route.json
如果是使用 warp ，则 "outbound":"warp-IPv4-out" 和  "outbound":"warp-IPv6-out"，如果本身解锁直连可以的话，就是 direct

<img width="1208" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/cf609900-ee50-4356-961f-2e182b5b7b24">
