### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by snakexgc** [fscarmen/sing-box#20]
1. 希望hy2能够支持使用自己的域名。（通过acme.sh申请证书）
2. 希望能够新增一个对每项协议进行参数修改的功能。（因为对于默认参数不合适的协议，只能手动进入sing-box的文件目录下进行调整，比较麻烦）
3. 希望能够直接输出可用于sfa，sfw，sfi等平台的配置文件。
 
感谢大佬的付出！脚本很好用！对于以上建议，也希望大佬能够考虑一下！

**Comment by fscarmen** [comment]
1. 脚本定位为傻瓜的，同时我也不喜欢acme证书，既要找域名，又要空闲 80/443 端口出来，遇到 nat 机就不行了。我也不想增加交互了，因为每增加一个交互，用户体验就 -n 倍的
2. 同1，我也考虑过专业安装模式，每个协议都问3、4个参数，但如果我是用户，我是接受不了，小白也可能不了解其中的意思，所以后面放弃了。有能力的玩家可以安装每个协议专门基于每个协议官方内核的一键脚本，又或者像你一样手动改一下（现在每个协议是用最经典的方式了，我想手动改的用户会远远完全不改的用户少，所以少数服从多数）
3. 输出客户端的 outbound 已有，可以用 `sb -n` 显示；
没有处理 DNS / 路由 / 入站 这三个模块，因为每个用户要求不一样，如果需要完整模板，可以参照 https://t.me/ztvps/37
这点与 clash meta 一样，只输出节点部分，毕竟每人用的模板不一样。
