### ISSUE TITLE
节点订阅链接

### ISSUE THREAD

**Issue by LReion** [fscarmen/sing-box#23]
我有域名，然后想通过域名订阅节点信息。复制过去有点麻烦。。。

**Comment by fscarmen** [comment]
我现在的做法都是把文件放在 onedriver，使用网盘直链网把网址变成可以读取，这样各个客户端来订阅更新的。

**Comment by LReion** [comment]
请问一下这个怎么弄。。。

**Comment by fscarmen** [comment]
油管搜一下如何在网盘做订阅的视频，我是把文件放在 onedriver，再用网盘直链助手，把分享的url转化为可以下载的url，这样实现的。

https://onedrive.gimhoy.com/

**Comment by LReion** [comment]
okk，谢谢。
