### ISSUE TITLE
Tuic5 的速度上不去

### ISSUE THREAD

**Issue by ainp** [fscarmen/sing-box#24]
对比了勇哥的脚本和您的。唯一的差别是勇哥的使用了自己域名证书。但速度有不小的差距，百思不解。

**Comment by fscarmen** [comment]
我的建议是你分几个时间，同一台机器测，记录一下数据值。
如果没有时间测，就使用甬哥脚本，心里踏实。

**Comment by fscarmen** [comment]
有没有测试过，是不是甬哥脚本一定会快点？
