### ISSUE TITLE
F大 可否把内置 warp 链式代理解锁 chatGPT改为手动可选功能

### ISSUE THREAD

**Issue by zzrove** [fscarmen/sing-box#25]
默认开启  会导致原vps的dns解锁偶然出现失败  我反复试了好多次 或者有什么办法可以关闭此脚本自带的链式代理 谢谢 一键singbox非常好用  又不想舍弃此脚本 但是又不想使用链式代理

**Comment by zzrove** [comment]
多谢f大深夜解答 感谢🙏

**Comment by fscarmen** [comment]
> 多谢f大深夜解答 感谢🙏

改之后，记得两次 `sb -o` 来关和开一次以生效。
