### ISSUE TITLE
同步升级sing box后，查看节点信息为空

### ISSUE THREAD

**Issue by wjcwukong** [fscarmen/sing-box#26]
1 .  查看节点信息 (sb -n) 
 2 .  关闭 Sing-box (sb -o) 
 3 .  更换监听端口 (sb -p) 
 4 .  同步 Sing-box 至最新版本 (sb -v) 
 5 .  升级内核、安装BBR、DD脚本 (sb -b) 
 6 .  增加 / 删除协议 (sb -r) 
 7 .  卸载 (sb -u) 
 8 .  安装 ArgoX 脚本 (argo + xray) [https://github.com/fscarmen/argox] 
 9 .  安装 sba 脚本 (argo + sing-box) [https://github.com/fscarmen/sba] 
 10.  安装 TCP brutal 
 0 .  退出 

 请选择: 1
*******************************************
┌────────────────┐
│                │
│     V2rayN     │
│                │
└────────────────┘

*******************************************
┌────────────────┐
│                │
│  Shadowrocket  │
│                │
└────────────────┘
----------------------------

*******************************************
┌────────────────┐
│                │
│   Clash Meta   │
│                │
└────────────────┘
----------------------------

*******************************************
┌────────────────┐
│                │
│    NekoBox     │
│                │
└────────────────┘

*******************************************
┌────────────────┐
│                │
│    Sing-box    │
│                │
└────────────────┘
----------------------------
{
  "outbounds":[
  ]
}

 完整模板可参照: https://t.me/ztvps/37

 脚本当天运行次数: 468，累计运行次数: 6821

**Comment by fscarmen** [comment]
加了两个协议，可能对旧的有影响，你运行 `cat /etc/sing-box/list`

**Comment by wjcwukong** [comment]
> 加了两个协议，可能对旧的有影响，你运行 `cat /etc/sing-box/list`

Thanks♪(･ω･)ﾉ

**Comment by fscarmen** [comment]
> > 加了两个协议，可能对旧的有影响，你运行 `cat /etc/sing-box/list`
> 
> Thanks♪(･ω･)ﾉ

如果还是不行，可以记录一下原来的 uuid ，节点名，开始端口号，如果有 reality的记录一下 reality 的一对key，重新安装即可，也很快的。
