### ISSUE TITLE
1.1.0 全新安装 singbox无法启动 log文件无任何信息

### ISSUE THREAD

**Issue by MurasameCyan** [fscarmen/sing-box#27]
脚本版本: v1.1.0
 功能新增: 1. 增加 [ H2 + Reality ] 和 [ gRPC + Reality ]，需要重新安装; 2. 由于 Sing-box 更新极快，将使用 beta 版本替代 alpha; 3. 支持 TCP brutal， 并提供官方安装脚本
 系统信息:
         当前操作系统: Debian GNU/Linux 12 (bookworm)
         内核: 6.1.0-12-cloud-amd64
         处理器架构: amd64v3
         虚拟化: kvm 
         IPv4: 11111 日本  Google LLC 
         IPv6:      
         Sing-box: 关闭  version: 1.7.0-beta.4 
         使用端口: 8881 - 8885

**Comment by fscarmen** [comment]
`systemctl enable --now sing-box; systemctl status sing-box` 看看

**Comment by MurasameCyan** [comment]
![image](https://github.com/fscarmen/sing-box/assets/50967145/1a8a2f7b-6ef2-4952-a480-48ad872e0a72)
  Sing-box: 关闭  

无效

**Comment by MurasameCyan** [comment]
![image](https://github.com/fscarmen/sing-box/assets/50967145/775b0a84-909d-420d-877e-cd3d37ce1cec)
无效

**Comment by fscarmen** [comment]
这个不是运行起来了吗？ `ss -nlutp`  看看有没有 sing-box 的任务？

**Comment by MurasameCyan** [comment]
![image](https://github.com/fscarmen/sing-box/assets/50967145/873e9c11-a216-450a-ad71-b6c870812cc3)
![image](https://github.com/fscarmen/sing-box/assets/50967145/96fd1aeb-660b-4116-af94-97699a8b9b0e)
并没有

**Comment by MurasameCyan** [comment]
![image](https://github.com/fscarmen/sing-box/assets/50967145/b3121373-efc0-411a-8b33-399fc74332cd)
log也是空的

**Comment by fscarmen** [comment]
你卸载再安装多次看看，再不行发一下 ssh 我看看是什么情况 fscarmen@gmail.com

**Comment by MurasameCyan** [comment]
已发

**Comment by fscarmen** [comment]
已处理，官方的 v1.7.0-beta.4 炸了。
