### ISSUE TITLE
一键脚本能否在安装时增加一些选项？

### ISSUE THREAD

**Issue by kay-zhu** [fscarmen/sing-box#3]
比如：
1.只安装某个协议，现在是一下安装了众多协议，实在没有必要
2.自选回落域名
3.端口号1-65555间随机
4.uuid随机生成
5.配置文件合并成一个config.json

谢谢！

**Comment by fscarmen** [comment]
1. 2023.10.23 beta2 支持单选，多选或全选协议
2. 本脚本定位为真小白用户，即使没有域名也能安装，免去 cf 设置 dns 的操作
3. 完全没有必须，现在为 1000-65525，低端口号一般为系统端口"（system ports）或"知名端口"（well-known ports），而本脚本因为多协议，所以不能用到65535这么大，因为这样后面就没有得号了，由1000-65525中间有 64536个端口，本脚本最多占用10个，完全足够了。开始端口是自定义，如果不选默认8881，是由于让用户更好的规划
4. uuid是随机生成的
5. 由于json的内容过多，合并成一个config.json，很不方便用户更改和加料。
