### ISSUE TITLE
请求增加一个socks5协议

### ISSUE THREAD

**Issue by photkey** [fscarmen/sing-box#31]
SOCKS5协议在使用指纹浏览器时会临时使用一下

**Comment by fscarmen** [comment]
之所以没有考虑加 http 和  socks5 进去，是考虑到本脚本的用户以正常科学的小白为主。他们很多会全选的协议的而不是有选择的选，这样会导致http和socks5暴露在公网，这样会大幅增加 ip 被墙的风险，所以还是没有加了。有需要的话，可以考虑使用单协议的sb脚本，比如：https://github.com/TinrLin/sing-box
