### ISSUE TITLE
安装TCP brutal  提示这个

### ISSUE THREAD

**Issue by sxml** [fscarmen/sing-box#32]
完蛋了小白痛苦
bash <(curl -fsSL https://tcp.hy2.sh): error: Cannot install 'linux-headers-5.10.0-8-amd64' with detected package manager, please install it manually.

**Comment by akaagiao1** [comment]
这个是你系统的问题

**Comment by fscarmen** [comment]
请来这里提 issue ，我只是作引用而已，建议你可以升级一下linux内核再试试。

https://github.com/apernet/tcp-brutal
