### ISSUE TITLE
如何修改配置文件？

### ISSUE THREAD

**Issue by photkey** [fscarmen/sing-box#33]
直接修改 `/etc/sing-box/conf` 这个目录下的文件就可以了吗？
比方我需要添加bound，是不是直接加到`01_outbounds.json`这个文件里；修改route就直接改`02_route.json`？

**Comment by EluneAdore1** [comment]
对
zsbd

**Comment by fscarmen** [comment]
建议改之前做好备份，当初设计配置文件分开，也是为了让大家更容易改。
