### ISSUE TITLE
beta版本已经滞后了，请考虑增加稳定版选项

### ISSUE THREAD

**Issue by silentxrture** [fscarmen/sing-box#34]
rtrt

**Comment by fscarmen** [comment]
我是摸不出规律了。一会儿 beta ，一会儿 rc ，一会儿 alpha，中间还夹着些不带后缀的正式版

```
tag_name": "v1.8.0-alpha.17",
tag_name": "v1.8.0-alpha.16",
tag_name": "v1.7.4",
tag_name": "v1.8.0-alpha.15",
tag_name": "v1.8.0-alpha.13",
tag_name": "v1.8.0-alpha.12",
tag_name": "v1.8.0-alpha.11",
tag_name": "v1.8.0-alpha.10",
tag_name": "v1.7.2",
tag_name": "v1.8.0-alpha.8",
tag_name": "v1.8.0-alpha.7",
tag_name": "v1.8.0-alpha.6",
tag_name": "v1.7.1",
tag_name": "v1.8.0-alpha.5",
tag_name": "v1.8.0-alpha.1",
tag_name": "v1.7.0",
tag_name": "v1.7.0-rc.3",
tag_name": "v1.6.7",
tag_name": "v1.7.0-rc.2",
tag_name": "v1.7.0-rc.1",
tag_name": "v1.6.6",
tag_name": "v1.7.0-beta.5",
tag_name": "v1.7.0-beta.4",
tag_name": "v1.7.0-beta.3",
tag_name": "v1.6.5",
tag_name": "v1.7.0-beta.2",
tag_name": "v1.7.0-beta.1",
tag_name": "v1.6.4",
tag_name": "v1.6.3",
tag_name": "v1.7.0-alpha.11",
```

**Comment by silentxrture** [comment]
> 我是摸不出规律了。一会儿 beta ，一会儿 rc ，一会儿 alpha，中间还夹着些不带后缀的正式版
> 
> ```
> tag_name": "v1.8.0-alpha.17",
> tag_name": "v1.8.0-alpha.16",
> tag_name": "v1.7.4",
> tag_name": "v1.8.0-alpha.15",
> tag_name": "v1.8.0-alpha.13",
> tag_name": "v1.8.0-alpha.12",
> tag_name": "v1.8.0-alpha.11",
> tag_name": "v1.8.0-alpha.10",
> tag_name": "v1.7.2",
> tag_name": "v1.8.0-alpha.8",
> tag_name": "v1.8.0-alpha.7",
> tag_name": "v1.8.0-alpha.6",
> tag_name": "v1.7.1",
> tag_name": "v1.8.0-alpha.5",
> tag_name": "v1.8.0-alpha.1",
> tag_name": "v1.7.0",
> tag_name": "v1.7.0-rc.3",
> tag_name": "v1.6.7",
> tag_name": "v1.7.0-rc.2",
> tag_name": "v1.7.0-rc.1",
> tag_name": "v1.6.6",
> tag_name": "v1.7.0-beta.5",
> tag_name": "v1.7.0-beta.4",
> tag_name": "v1.7.0-beta.3",
> tag_name": "v1.6.5",
> tag_name": "v1.7.0-beta.2",
> tag_name": "v1.7.0-beta.1",
> tag_name": "v1.6.4",
> tag_name": "v1.6.3",
> tag_name": "v1.7.0-alpha.11",
> ```

lol，干脆就正式版好了，全家桶稳定比较重要吧

**Comment by fscarmen** [comment]
我问了一下，知道逻辑了  alpha --> beta --> rc --> 正式版，考虑到正式版比较落后了，可能会用最新的，就是容易翻车炸锅（指旧版本的配置文件在新版本上不能用），之前已经试过一次了，有点怕。

**Comment by jtsang4** [comment]
可以增加支持手动指定 sing-box 版本吗，现在更新到 beta 版本客户端还没支持，没法降级导致用不上了……

**Comment by fscarmen** [comment]
> 可以增加支持手动指定 sing-box 版本吗，现在更新到 beta 版本客户端还没支持，没法降级导致用不上了……

你嫌版本过新，楼主嫌版本过旧。

**Comment by jtsang4** [comment]
> > 可以增加支持手动指定 sing-box 版本吗，现在更新到 beta 版本客户端还没支持，没法降级导致用不上了……
> 
> 你嫌版本过新，楼主嫌版本过旧。

哈哈，能自定义版本也许能解决问题

**Comment by fscarmen2** [comment]
现在v1.8.0-beta.1 增加了一些set_rule 和 缓存，导致配置文件与正式版v1.7.4不兼容的。我的设计是等1.8.0正式版出来后，更新一下，安装和升级时可以选项最新的正式版或者测试版，看作者的进度，预计是半个月左右。

**Comment by fscarmen** [comment]
现在v1.8.0-beta.1 增加了一些set_rule 和 缓存，导致配置文件与正式版v1.7.4不兼容的。我的设计是等1.8.0正式版出来后，更新一下，安装和升级时可以选项最新的正式版或者测试版，看作者的进度，预计是半个月左右。

**Comment by jesseqca** [comment]
> 现在v1.8.0-beta.1 增加了set_rule 和 缓存等更新，导致配置文件与正式版v1.7.4不兼容的。我的设计是等1.8.0正式版出来后，更新脚本，安装和升级时可以选项最新的正式版或者测试版，看作者的进度，预计是半个月左右。

v1.8.0-beta.1 有大问题，全新安装启动不了 sing-box， 同步升级到这个版本也一样，我测了两台 vps 都有这个问题，已经提了 issue，麻烦大佬抽空看看
