### ISSUE TITLE
sing-box 关闭后启动不了，卸载重装也一样，重启 vps 也不行

### ISSUE THREAD

**Issue by jesseqca** [fscarmen/sing-box#35]
起因是突然 报主机内存暴涨，查了一下是 sing-box 占用过高，然后手动停了，再开启就不行了。提示开启成功，查看状态其实是关闭，试了 2 台 vps 都是这样。

更新；

问题定位到了，启动不了的是因为sing-box 同步升级到version: 1.8.0-beta.1 

旧版本version: 1.7.0-beta.5  能正常开启关闭

**Comment by gdyan2022** [comment]
同样的问题  报错： FATAL[0000] merge config at /etc/sing-box/conf/00_log.json: decode source: EOF
