### ISSUE TITLE
安装TCP brutal再去部署节点，就会自动使用TCP brutal是吗？

### ISSUE THREAD

**Issue by mekkhalawang** [fscarmen/sing-box#37]

**Comment by fscarmen** [comment]
是的

**Comment by akaagiao1** [comment]
> 是的

大佬，TCP brutal只要在server配置·吗·,我看生成的sing-box客户端没配置TCP brutal啊

**Comment by fscarmen** [comment]
tcp brutal 主要是影响上传为主，而作为科学的客户端，上传数据量极少的。
同时 brutal 内能在 linux 才能使用，而客户端多半是 windows 或者 macos 或者 手机，所以安装不了 brutal。

https://github.com/apernet/tcp-brutal/blob/master/README.zh.md#%E5%85%BC%E5%AE%B9%E6%80%A7

### 兼容性

TCP Brutal 只是 TCP 的拥塞控制算法，并不修改 TCP 协议本身。客户端和服务端可以只有单边安装内核模块。拥塞控制算法控制的是数据的发送，而考虑到代理用户通常下载的数据量远大于上传，只在服务端使用 TCP Brutal 就可以获得大部分的收益。（客户端使用 TCP Brutal 可以获得更好的上传速度，但很多人使用的是 Windows, macOS 或手机，安装内核模块往往不现实。）

**Comment by akaagiao1** [comment]
原来如此感谢你

**Comment by akaagiao1** [comment]
> https://github.com/apernet/tcp-brutal/blob/master/README.zh.md#%E5%85%BC%E5%AE%B9%E6%80%A7

那我就不纠结了
