### ISSUE TITLE
vmess回源失败

### ISSUE THREAD

**Issue by bettswang** [fscarmen/sing-box#39]
如题，按照说明指示，安装配置好sing-box全家桶，vless和vmess使用同一个域名，以及在cloudflare上设置好回源端口，vless可以使用，vmess无法使用。客户端使用该节点服务，报错。
![图片](https://github.com/fscarmen/sing-box/assets/43665641/d20c9bc6-4e55-4b29-94b3-0104cd472469)

**Comment by fscarmen** [comment]
不同域名，不回回源端口

**Comment by bettswang** [comment]
> 不同域名，不回回源端口
意思是不能使用同一个域名吗
