### ISSUE TITLE
I need the 4g carrier's sni to use for free

### ISSUE THREAD

**Issue by Ley-VN** [fscarmen/sing-box#4]
Your configuration although I filled in is dl.kgvn.garenanow.com. but it has no effect on tuic and hy2

**Comment by fscarmen** [comment]
Maybe your vps provider limits udp traffic.

**Comment by Ley-VN** [comment]
> Có thể nhà cung cấp vps của bạn giới hạn lưu lượng truy cập udp.

Use vps ovh cloud.
