### ISSUE TITLE
v2rayN中使用tuic和shadowtls连接未成功

### ISSUE THREAD

**Issue by kelekekou8** [fscarmen/sing-box#40]
为什么在v2rayN中使用tuic和shadowtls无法连接成功，操作时更新了内核和v2rayN客户端。能不能提供一个简单的操作说明。谢谢大佬。

**Comment by fscarmen** [comment]
你安装之后，出来节点信息的时候，下面有写着用什么内核的，下载过去，在v2rayN运行的时候调用该内核，并使用相应的配置信息。详细的教程你可以油管或者google一下v2rayN如何使用 sing-box 内核等，我这里不重复做轮子，写太详细的客户端使用教程了。

**Comment by kelekekou8** [comment]
谢谢，在nekobox所有节点都可用，唯有vless节点就是 8888端口的那个，ping是通的但无法连接。已解析域名并回源端口8888.请大佬指点。
