### ISSUE TITLE
nekobox中vless ws tls节点链接（8888端口那个）不能连接

### ISSUE THREAD

**Issue by kelekekou8** [fscarmen/sing-box#41]
在nekobox提供的所有节点链接都可用，唯有一个vless节点就是 8888端口的那个，ping是通的但无法连接。已解析域名并回源端口8888.请大佬指点。

**Comment by fscarmen** [comment]
不太清楚哦，看看域名等有没有设置错，在脚本处是不是设置端口为8888

**Comment by kelekekou8** [comment]
补充一下，在vless这个8888端口节点，v2ray里边也不能连接，我考虑是脚本某些配置问题。其它节点都没有问题。

**Comment by fscarmen** [comment]
以下这个节点我也是用 8888 的啊
![image](https://github.com/fscarmen/sing-box/assets/62703343/73ea8207-fed9-420f-8d82-8eb912f8f113)


```
vless://22fa01ec-dd00-4ff1-8ff2-66779ef98e67@cn.azhz.eu.org:443?encryption=none&security=tls&sni=l-test.formyvmess.tk&type=ws&host=l-test.formyvmess.tk&path=%2F22fa01ec-dd00-4ff1-8ff2-66779ef98e67-vless%3Fed%3D2048#woiden.localhost
```

**Comment by honue** [comment]
遇到同样问题，确认cf侧端口，域名设置正确，clash meta测试不通

**Comment by kelekekou8** [comment]
套CDN的vmess和vless节点无法连接原因找到了！是因为在CF上端口回源后有可能等段时间才生效，一般第二天就没事了。

**Comment by fscarmen** [comment]
除非cf出问题，一般都马上生效的哦，不可能等一天的

**Comment by helema** [comment]
同样问题,第8个vless+ws+tls,无法连接

**Comment by MaleicAcid** [comment]
遇到了同样的问题, 只有vmess和vless ws tls节点无法连接, 已经正确设置了origin规则

**Comment by fscarmen** [comment]
> 遇到了同样的问题, 只有vmess和vless ws tls节点无法连接, 已经正确设置了origin规则

换个优选看看

https://github.com/fscarmen/sing-box/issues/96#issuecomment-2136359900
