### ISSUE TITLE
sing-box节点配置文件导到安卓无法使用，用得1.8版本的。请指教

### ISSUE THREAD

**Issue by kelekekou8** [fscarmen/sing-box#42]

**Comment by fscarmen** [comment]
安卓版本的sing-box是1.8吗？我没试过的，都在pc和ios试，你再研究一下，找找官方或高海的模板看看

**Comment by fscarmen** [comment]
先判断一下节点用其他客户端通不通，以确认是节点问题还是客户端的问题，1.8对于节点的信息没有变动的
