### ISSUE TITLE
NaiveProxy

### ISSUE THREAD

**Issue by l3617** [fscarmen/sing-box#44]
大佬可以增加NaiveProxy协议吗，如果可以的话

**Comment by fscarmen** [comment]
我有点忘记当初为什么没有做了，好像是因为 NaiveProxy 不能用自签，要授权机构颁发的证书，与本项目定位不符！

**Comment by l3617** [comment]
> 我有点忘记当初为什么没有做成，是因为NaiveProxy不能用自签，要授权机构颁发的证书，与本项目定位不符！

是的，NaiveProxy的证书不能自签，不行就算了

**Comment by fscarmen** [comment]
https://github.com/fscarmen/sing-box/commit/9f7462f9da38fa453b8285aa9ce9c356832d5b24

2026.4.25

v1.3.10 feat: add naive protocol support
- add naive to protocol and node tag lists
- include naive in quick install and protocol reload flows
- generate naive inbound config with username/password auth
- add 200-day certificate generation and refresh logic for naive
- export naive nodes for Shadowrocket, V2RayN, and sing-box clients
- add client compatibility notes for NaiveProxy outbound

v1.3.10 feat: 增加 naive 协议支持

- 将 naive 加入协议列表和节点标签
- 支持极速安装与协议重载流程选择 naive
- 生成带用户名 / 密码认证的 naive 入站配置
- 为 naive 增加 200 天证书生成与自动刷新逻辑
- 导出 Shadowrocket、V2RayN 和 sing-box 客户端的 naive 节点
- 增加 NaiveProxy 出站客户端兼容性提示
