### ISSUE TITLE
安装 TCP brutal 时出错

### ISSUE THREAD

**Issue by ainp** [fscarmen/sing-box#45]
Checking linux-headers ... not installed
Try to install linux-headers for 6.1.0-10-cloud-amd64 ... 
Installing missing dependence 'linux-headers-6.1.0-10-cloud-amd64' with 'apt -y --no-install-recommends install' ... 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-6.1.0-10-cloud-amd64
E: Couldn't find any package by glob 'linux-headers-6.1.0-10-cloud-amd64'
bash <(curl -fsSL https://tcp.hy2.sh): error: Cannot install 'linux-headers-6.1.0-10-cloud-amd64' with detected package manager, please install it manually.

**Comment by fscarmen** [comment]
去tcp btutal那提issue

**Comment by ainp** [comment]
谢谢
