### ISSUE TITLE
兄弟看看能不能合并一下TinrLin这个脚本？

### ISSUE THREAD

**Issue by sw19999** [fscarmen/sing-box#47]
这个脚本也简单好用，可以每个协议自定义端口。但是不如兄弟的，不可以输出小火箭和nekobox链接。也不支持任意端口回源。
也能安装WireGuard解锁，但是不能任意端口回源，兄弟看看能不能修改一下，能任意端口 Origin Rules 回源。

原作者：Github.com/TinrLin （已经删库了）

我备份了：https://github.com/sw19999/singbox

**Comment by fscarmen** [comment]
回源是使用支持 ws 传输方式的才行啊，直连的比如 hy2，reality 等都不行的，我也不明白你的意思 ，你安装的时候，设置定自义端口，再在cf里设置 origin rules 不是就可以了吗？看了下 TinrLin 的非常专业，已经超出我能力了。
简单对比如下（只代表我自己的想法 ）
| sing-box 脚本 | TinrLin | fscarmen |
| --- | --- | --- |
| 定位 | 专业玩家，喜欢很多个性化选项的 | 小白用户，喜欢无脑回车，什么都处理好的 |
| 同时运行多协议 | 否 | 是，可以同时存在 hy2, reality, tuic 等 |
| 协议支持 | 非常全 | 主流经典 |
| 各协议的个性化选项 | 是，由于单协议，比较好做二级交互以支持个性化选项，像 vless 同时支持 gRPC, 是否开启 ECH 等  | 否,每个协议只选用“最”经典的，因为9个协议，每个协议再有3、4个交互的话，就是有30多个交互，用户一早 ctrl+c 了 |
| 证书 | 同时支持申请认证机构颁发的证书和自签 | 定位的原因，只支持自签，选择了省心快的方式 |
| Sing-box 版本 | 同时支持正式版和测试版 | 优先大版本，再使用该版本下最新的，无区分正式和测试 |
| 节点输出 | clash 完整配置信息和 手机/pc 完美的 sing-box 信息，但 sing-box 在1.8.0 有几处配置上的修动，而脚本缺乏维护导致 sing-box 配置使用不了 | 输出 neko / 小火箭 / clash / v2ray / sing-box 的节点部分信息，其中 clash 和  sing-box 并不能直接运行，需要加到原有使用中的配置文件中运行 |

BTW
* 运行命令你那里错了，应该是: `bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)`
* 安装之前，要先处理一些依赖: `apt install -y net-tools jq`



```
bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  262k  100  262k    0     0   547k      0 --:--:-- --:--:-- --:--:--  547k
╔════════════════════════════════════════════════════════════════════════╗
║ 作者： Mr. xiao                                                        ║
║ 博客地址: https://tinrlin.com                                          ║
║ 项目地址: https://github.com/TinrLin                                   ║
║ Telegram 群组: https://t.me/mrxiao758                                  ║
║ YouTube频道: https://youtube.com/@Mr_xiao502       Version：1.2        ║
╠════════════════════════════════════════════════════════════════════════╣
║ 请选择要执行的操作：                                                   ║
║ [1]  SOCKS                              [2]   Direct                   ║
║ [3]  HTTP                               [4]   VMess                    ║
║ [5]  VLESS                              [6]   TUIC                     ║
║ [7]  Juicity                            [8]   Trojan                   ║
║ [9]  Hysteria                           [10]  Hysteria2                ║
║ [11] ShadowTLS                          [12]  NaiveProxy               ║
║ [13] Shadowsocks                        [14]  WireGuard                ║
║ [15] 查看节点信息                       [16]  更新内核                 ║
║ [17] 更新脚本                           [18]  更新证书                 ║
║ [19] 重启服务                           [20]  节点管理                 ║
║ [21] 卸载                               [0]   退出                     ║
╚════════════════════════════════════════════════════════════════════════╝
请选择 [0-21]: 5
BBR is already enabled, skipping configuration.
请选择节点类型 (默认1)：     
1). VLESS+TCP
2). VLESS+WebSocket
3). VLESS+gRPC
4). VLESS+HTTPUpgrade
5). VLESS+Vision+REALITY
6). VLESS+H2C+REALITY
7). VLESS+gRPC+REALITY
请选择[1-7]: 2
请输入监听端口 (默认443): 8754
监听端口：8754
请输入UUID（默认随机生成）: 
UUID：e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
是否继续添加用户？(Y/N，默认N): 
请输入 ws 路径 (默认随机生成): 
是否开启多路复用？(Y/N，默认为Y): y
是否开启 TCP Brutal？(Y/N，默认为N): 
No firewall configuration detected or firewall is not enabled, skipping firewall configuration.
VLESS 节点配置信息：
==============================================================================
服务器地址: 148.113.1.115
------------------------------------------------------------------------------
监听端口: 8754
------------------------------------------------------------------------------
UUID列表:
e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
------------------------------------------------------------------------------
传输协议: ws
路径: /BhvOnhwj
==============================================================================
配置信息已保存至 /usr/local/etc/sing-box/output.txt
Clash配置文件已保存至 /usr/local/etc/sing-box/clash.yaml，请下载使用！
手机端配置文件已保存至/usr/local/etc/sing-box/phone_client.json，请下载后使用！
电脑端配置文件已保存至/usr/local/etc/sing-box/win_client.json，请下载后使用！
```

**Comment by l3617** [comment]
可惜了，我也用过这脚本，作者突然就删库了

**Comment by sw19999** [comment]
> 回源是使用支持 ws 传输方式的才行啊，直连的比如 hy2，reality 等都不行的，我也不明白你的意思 ，你安装的时候，设置定自义端口，再在cf里设置 origin rules 不是就可以了吗？看了下 TinrLin 的非常专业，已经超出我能力了。 简单对比如下（只代表我自己的想法 ）
> 
> sing-box 脚本	TinrLin	fscarmen
> 定位	专业玩家，喜欢很多个性化选项的	小白用户，喜欢无脑回车，什么都处理好的
> 同时运行多协议	否	是，可以同时存在 hy2, reality, tuic 等
> 协议支持	非常全	主流经典
> 各协议的个性化选项	是，由于单协议，比较好做二级交互以支持个性化选项，像 vless 同时支持 gRPC, 是否开启 ECH 等	否，每个协议只选用“最”经典的，因为9个协议，每个协议再有3、4个交互的话，就是有30多个交互，用户一早 ctrl+c 了
> 证书	同时支持申请认证机构颁发的证书和自签	定位的原因，只支持自签，选择了省心快的方式
> Sing-box 版本	同时支持正式版和测试版	优先大版本，再使用该版本下最新的，无区分正式和测试
> 节点输出	clash 完整配置信息和 手机/pc 完美的 sing-box 信息，但 sing-box 在1.8.0 有几处配置上的修动，而脚本缺乏维护导致 sing-box 配置使用不了	输出 neko / 小火箭 / clash / v2ray / sing-box 的节点部分信息，其中 clash 和 sing-box 并不能直接运行，需要加到原有使用中的配置文件中运行
> 脚本行数	5000行	2150行，只是TinrLin的 43%，间接反映 TinrLin 的功能相对多得多
> BTW
> 
> * 运行命令你那里错了，应该是: `bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)`
> * 安装之前，要先处理一些依赖: `apt install -y net-tools jq`
> * 我找到个应该是续着的脚本，不过是英文版的 https://github.com/TheyCallMeSecond/sing-box-manager
> 
> ```
> bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  262k  100  262k    0     0   547k      0 --:--:-- --:--:-- --:--:--  547k
> ╔════════════════════════════════════════════════════════════════════════╗
> ║ 作者： Mr. xiao                                                        ║
> ║ 博客地址: https://tinrlin.com                                          ║
> ║ 项目地址: https://github.com/TinrLin                                   ║
> ║ Telegram 群组: https://t.me/mrxiao758                                  ║
> ║ YouTube频道: https://youtube.com/@Mr_xiao502       Version：1.2        ║
> ╠════════════════════════════════════════════════════════════════════════╣
> ║ 请选择要执行的操作：                                                   ║
> ║ [1]  SOCKS                              [2]   Direct                   ║
> ║ [3]  HTTP                               [4]   VMess                    ║
> ║ [5]  VLESS                              [6]   TUIC                     ║
> ║ [7]  Juicity                            [8]   Trojan                   ║
> ║ [9]  Hysteria                           [10]  Hysteria2                ║
> ║ [11] ShadowTLS                          [12]  NaiveProxy               ║
> ║ [13] Shadowsocks                        [14]  WireGuard                ║
> ║ [15] 查看节点信息                       [16]  更新内核                 ║
> ║ [17] 更新脚本                           [18]  更新证书                 ║
> ║ [19] 重启服务                           [20]  节点管理                 ║
> ║ [21] 卸载                               [0]   退出                     ║
> ╚════════════════════════════════════════════════════════════════════════╝
> 请选择 [0-21]: 5
> BBR is already enabled, skipping configuration.
> 请选择节点类型 (默认1)：     
> 1). VLESS+TCP
> 2). VLESS+WebSocket
> 3). VLESS+gRPC
> 4). VLESS+HTTPUpgrade
> 5). VLESS+Vision+REALITY
> 6). VLESS+H2C+REALITY
> 7). VLESS+gRPC+REALITY
> 请选择[1-7]: 2
> 请输入监听端口 (默认443): 8754
> 监听端口：8754
> 请输入UUID（默认随机生成）: 
> UUID：e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
> 是否继续添加用户？(Y/N，默认N): 
> 请输入 ws 路径 (默认随机生成): 
> 是否开启多路复用？(Y/N，默认为Y): y
> 是否开启 TCP Brutal？(Y/N，默认为N): 
> No firewall configuration detected or firewall is not enabled, skipping firewall configuration.
> VLESS 节点配置信息：
> ==============================================================================
> 服务器地址: 148.113.1.115
> ------------------------------------------------------------------------------
> 监听端口: 8754
> ------------------------------------------------------------------------------
> UUID列表:
> e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
> ------------------------------------------------------------------------------
> 传输协议: ws
> 路径: /BhvOnhwj
> ==============================================================================
> 配置信息已保存至 /usr/local/etc/sing-box/output.txt
> Clash配置文件已保存至 /usr/local/etc/sing-box/clash.yaml，请下载使用！
> 手机端配置文件已保存至/usr/local/etc/sing-box/phone_client.json，请下载后使用！
> 电脑端配置文件已保存至/usr/local/etc/sing-box/win_client.json，请下载后使用！
> ```



我改一下说明就是了，加上 net-tools 依赖，其它依赖都有了，另外他这个脚本可以多协议共存的。跟兄弟的一样，安装好可以继续添加多协议，也可以跟兄弟一样，随时减少某个协议的。

回源我添加的就是vmess ws协议，也安装了WireGuard，端口也设置了，但是连不上。

**Comment by fscarmen** [comment]
> 
> 我改一下说明就是了，加上 net-tools 依赖，其它依赖都有了，另外他这个脚本可以多协议共存的。跟兄弟的一样，安装好可以继续添加多协议，也可以跟兄弟一样，随时减少某个协议的。
> 
> 回源我添加的就是vmess ws协议，也安装了WireGuard，端口也设置了，但是连不上。

建议你到后面维护项目的这里发issue看看回源如何处理

[ https://github.com/TheyCallMeSecond/sing-box-manager](https://github.com/TheyCallMeSecond/sing-box-manager)

**Comment by sw19999** [comment]
> > 我改一下说明就是了，加上 net-tools 依赖，其它依赖都有了，另外他这个脚本可以多协议共存的。跟兄弟的一样，安装好可以继续添加多协议，也可以跟兄弟一样，随时减少某个协议的。
> > 回源我添加的就是vmess ws协议，也安装了WireGuard，端口也设置了，但是连不上。
> 
> 建议你到后面维护项目的这里发issue看看回源如何处理
> 
> [ https://github.com/TheyCallMeSecond/sing-box-manager](https://github.com/TheyCallMeSecond/sing-box-manager)

好的，我去那边问问

**Comment by fscarmen** [comment]
> 建议你到后面维护项目的这里发issue看看回源如何处理
> 
> [ https://github.com/TheyCallMeSecond/sing-box-manager](https://github.com/TheyCallMeSecond/sing-box-manager)

看了一下，可能 TheyCallMeSecond 才是原创者，TinrLin 可能就是把别人的 logo 换成自己的信息，英文用翻译工具转为中文而已，晕，看错人了。

**Comment by smith-stack** [comment]
> > 回源是使用支持ws传输方式的才行啊，直连的比如hy2，现实等都不行的，我也不明白你的意思，你安装的时候，设置设置自义端口，再在cf里设置原点规则不是就可以了吗？看了下TinrLin的非常专业，已经超出了我的能力了。简单对比如下（只代表我自己的想法）
> > sing-box 脚本 TinrLin fscarmen
> > 定位专业玩家，喜欢很多个性化选项的小白，非常喜欢无脑回车，什么都处理好的
> > 同时运行多协议否是，可以同时存在 hy2、reality、tuic 等
> > 协议支持全主流经典
> > 各协议的个性化选项是，由于单协议，比较好做一线交互以支持个性化选项，像vless同时支持gRPC,是否开启ECH等否，每个协议只使用“最”经典的，因为9个协议，每个协议再有3、4个交互多个的话，就是有30个交互，用户一早ctrl+c了
> > 证书同时支持申请认证机构颁发的证书和自签定位的原因，只支持自签，选择了省心快的方式
> > 唱盒版本同时支持正式版和测试版优先大版本，再使用该版本下最新的，无区分正式和测试
> > 节点输出冲突完整配置信息和手机/电脑完美的唱-盒子信息，但sing-box在1.8.0 有几处配置上的修改，而脚本缺乏导致sing-box配置使用无法输出neko / 小火箭 / clang / v2ray / sing-box 的节点部分信息，其中clash 和 sing-box 并不能直接运行，添加到原有使用中的配置文件中运行
> > 脚本行数5000行2150行，只是TinrLin的43%，间接反映TinrLin的功能相对多分割
> > BTW
> > 
> > * 运行命令你那里错了，应该是：`bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)`
> > * 安装之前，要先处理一些依赖：`apt install -y net-tools jq`
> > * 我找到了一个应该是续着的脚本，不过是英文版的[https://github.com/ TheyCallMeSecond/ sing-box-manager](https://github.com/TheyCallMeSecond/sing-box-manager)
> > 
> > ```
> > bash <(curl https://raw.githubusercontent.com/sw19999/singbox/main/singbox.sh)
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> > 100  262k  100  262k    0     0   547k      0 --:--:-- --:--:-- --:--:--  547k
> > ╔════════════════════════════════════════════════════════════════════════╗
> > ║ 作者： Mr. xiao                                                        ║
> > ║ 博客地址: https://tinrlin.com                                          ║
> > ║ 项目地址: https://github.com/TinrLin                                   ║
> > ║ Telegram 群组: https://t.me/mrxiao758                                  ║
> > ║ YouTube频道: https://youtube.com/@Mr_xiao502       Version：1.2        ║
> > ╠════════════════════════════════════════════════════════════════════════╣
> > ║ 请选择要执行的操作：                                                   ║
> > ║ [1]  SOCKS                              [2]   Direct                   ║
> > ║ [3]  HTTP                               [4]   VMess                    ║
> > ║ [5]  VLESS                              [6]   TUIC                     ║
> > ║ [7]  Juicity                            [8]   Trojan                   ║
> > ║ [9]  Hysteria                           [10]  Hysteria2                ║
> > ║ [11] ShadowTLS                          [12]  NaiveProxy               ║
> > ║ [13] Shadowsocks                        [14]  WireGuard                ║
> > ║ [15] 查看节点信息                       [16]  更新内核                 ║
> > ║ [17] 更新脚本                           [18]  更新证书                 ║
> > ║ [19] 重启服务                           [20]  节点管理                 ║
> > ║ [21] 卸载                               [0]   退出                     ║
> > ╚════════════════════════════════════════════════════════════════════════╝
> > 请选择 [0-21]: 5
> > BBR is already enabled, skipping configuration.
> > 请选择节点类型 (默认1)：     
> > 1). VLESS+TCP
> > 2). VLESS+WebSocket
> > 3). VLESS+gRPC
> > 4). VLESS+HTTPUpgrade
> > 5). VLESS+Vision+REALITY
> > 6). VLESS+H2C+REALITY
> > 7). VLESS+gRPC+REALITY
> > 请选择[1-7]: 2
> > 请输入监听端口 (默认443): 8754
> > 监听端口：8754
> > 请输入UUID（默认随机生成）: 
> > UUID：e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
> > 是否继续添加用户？(Y/N，默认N): 
> > 请输入 ws 路径 (默认随机生成): 
> > 是否开启多路复用？(Y/N，默认为Y): y
> > 是否开启 TCP Brutal？(Y/N，默认为N): 
> > No firewall configuration detected or firewall is not enabled, skipping firewall configuration.
> > VLESS 节点配置信息：
> > ==============================================================================
> > 服务器地址: 148.113.1.115
> > ------------------------------------------------------------------------------
> > 监听端口: 8754
> > ------------------------------------------------------------------------------
> > UUID列表:
> > e3ef5bc7-09e3-473a-bbbf-e470a29ee0eb
> > ------------------------------------------------------------------------------
> > 传输协议: ws
> > 路径: /BhvOnhwj
> > ==============================================================================
> > 配置信息已保存至 /usr/local/etc/sing-box/output.txt
> > Clash配置文件已保存至 /usr/local/etc/sing-box/clash.yaml，请下载使用！
> > 手机端配置文件已保存至/usr/local/etc/sing-box/phone_client.json，请下载后使用！
> > 电脑端配置文件已保存至/usr/local/etc/sing-box/win_client.json，请下载后使用！
> > ```
> 
> 我改了一下说明就是了，加上net-tools依赖，其他依赖都有了，另外他这个脚本可以多协议共存的。跟兄弟一样，安装好可以继续添加多协议，也跟兄弟一样，随时减少某个协议的。
> 
> 回源我添加的就是vmess ws协议，也安装了WireGuard，端口也设置了，但是连不上。

老弟，我重新修改了一下，适配sing-box 1.90+了，你可以去试试https://github.com/smith-stack/sing-box

**Comment by smith-stack** [comment]
> 遗憾的是，我也用这个剧本，作者突然就删掉了

我重新修改了一下，脚本适配sing-box 1.90+了，你可以去尝试一下https://github.com/smith-stack/sing-box
