### ISSUE TITLE
请选择: 2 Sing-box 开启 失败

### ISSUE THREAD

**Issue by azyghqsavx** [fscarmen/sing-box#48]
请选择: 2 Sing-box 开启 失败
https://pic6.58cdn.com.cn/nowater/webim/big/n_v2b238a758309a49c0a52596d83087f2e8.png

**Comment by fscarmen** [comment]
手动运行看看
```
/etc/sing-box/sing-box run -C /etc/sing-box/conf/
```

**Comment by azyghqsavx** [comment]
> 手动运行看看
> 
> ```
gcvgycvgy:~# /etc/sing-box/sing-box run -C /etc/sing-box/conf/
FATAL[0009] start service: pre-start cache file: timeout



> 手动运行看看
> 
> ```
> /etc/sing-box/sing-box run -C /etc/sing-box/conf/
> ```

gcvgycvgy:~# /etc/sing-box/sing-box run -C /etc/sing-box/conf/
FATAL[0009] start service: pre-start cache file: timeout

**Comment by fscarmen** [comment]
你是不是升级版本，试试重装看看。
看上去 在 /etc/sing-box/cache.db 这个缓存文件报错。
