### ISSUE TITLE
求教，sing-box客户端中设置链式代理时shadowsocks如何设置？

### ISSUE THREAD

**Issue by MarinoAdmas** [fscarmen/sing-box#5]
请问你在设置sing-box链式代理的过程中shadowsocks的38881端口的流量是如何转发到shadowtls的8881端口的？是随便定义一个端口还是需要进行其他的配置？

**Comment by fscarmen** [comment]
详细说明以nekoray官方解析为准

**Comment by MarinoAdmas** [comment]
我遇到了和你之前同样的问题，只不过现在卡在如何打通Shadowsocks和shadowtls这一步，能否详细说一下两者的ip和端口配置？

**Comment by fscarmen** [comment]
项目的readme.md有，你看图文，通的

**Comment by MarinoAdmas** [comment]
谢谢
