### ISSUE TITLE
sing-box 好像和Nginx有冲突

### ISSUE THREAD

**Issue by ainp** [fscarmen/sing-box#51]
sing-box 和网站不能同时安装，查了一下是Nginx 造成的，能否配置一下nginx,让两者共存

**Comment by fscarmen** [comment]
本项目没有使用到 nginx 部分，完完全全只使用了 sing-box 官方二进制文件。如果有冲突，建议到 sing-box 或者  nginx 那里提 issue。

**Comment by ainp** [comment]
Thanks!
