### ISSUE TITLE
ipv4下不能正确检测到sing-box最新版本

### ISSUE THREAD

**Issue by gbinhe** [fscarmen/sing-box#52]
在一台ipv4 net机上，只能检测到1.8.1版sing-box，一直不能更新。今天在其上装了warp ipv6单栈，并设置为ipv6优先，检测到了1.8.5版，正常更新了。

**Comment by fscarmen** [comment]
我更换了 gh cdn，再试试。

**Comment by gbinhe** [comment]
试了新1.1.3版，现在完全正常了，多谢
