### ISSUE TITLE
hysteria2和tuic不工作

### ISSUE THREAD

**Issue by Neomanbeta** [fscarmen/sing-box#55]
![QQ截图20240219155356](https://github.com/fscarmen/sing-box/assets/33118244/895601c4-1ef7-4d94-8b5e-f15ad7c47011)
系统环境如图
我不知道是openvz的原因还是说是debian12的原因。
hysteria2和tuic安装完成以后都是不工作的，我用的测试客户端是nekobox。
其它的协议测试了几个，，包括用cf cdn的vless都是工作正常的。

**Comment by fscarmen** [comment]
虽然我没有 ovz 的机器，不过如果不是nat鸡，端口是开放的话，肯定是没有问题的哦，以下分别是 IPv4 和 IPv6 ，协议是 hy2 和 tuic，客户端用 nekobox 的，可以看到是有流量数据的。
<img width="1215" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/15838f15-2089-4149-85a2-d5a9302571e1">

**Comment by Neomanbeta** [comment]
非NAT机，所有端口都可用的。所以我也很挠头问题出在哪里，系统我也重装过了，反复测试了3次，也没找到问题在哪。

**Comment by Neomanbeta** [comment]
不是udp的原因，因为我重做之前用的一直都是hysteria和argo xray脚本，一直正常。
我close issue的原因是我昨天折腾了几次以后，我的vps貌似被墙了，国内ping不通了，无法继续测试，所以至于是什么原因，依然未知。
