### ISSUE TITLE
通过sb -n获取节点信息存在问题

### ISSUE THREAD

**Issue by liujf916** [fscarmen/sing-box#56]
通过sb -n获取节点中，Trojan节点名称将直接变为“ trojan”，并不是自定义的名称，但在初次部署是生成的节点信息是正常的。
虽然并不影响节点的正常使用。

**Comment by fscarmen** [comment]
为了规范之前代码和方便日后的扩展，上两天把 inbound.json 文件名和 tag 的做了统一，如果是你是之前已经安装的，不会影响使用，只会影响输出显示，你可以不用理会，如果是再重新安装，就不会出现这个问题。

https://github.com/fscarmen/sing-box/commit/7aa5deb0701170c868d068c18682b1364e2fa7d2

**Comment by liujf916** [comment]
> 为了规范之前代码和方便日后的扩展，上两天把 inbound.json 文件名和 tag 的做了统一，如果是你是之前已经安装的，不会影响使用，只会影响输出显示，你可以不用理会，如果是再重新安装，就不会出现这个问题。
> 
> [7aa5deb](https://github.com/fscarmen/sing-box/commit/7aa5deb0701170c868d068c18682b1364e2fa7d2)
我是指重装之后，通过sb-n获取到的NekoRay的Trojan的节点订阅链接还是有点小问题，就是获取到的Trojan节点tag都为“ trojan”并不是自己自定义的tag。其他类型的节点都为正常的自定义的tag，虽然不影响使用仅仅是tag名称的问题而已。

**Comment by liujf916** [comment]
如图我将tag自定义为BV_SG，Trojan节点订阅链接的tag是不正确的
![1111111](https://github.com/fscarmen/sing-box/assets/158129502/37152c50-fbab-423c-8d98-a38dda112fbf)

**Comment by fscarmen** [comment]
谢谢提醒，的确是漏了没有处理了，我已修复

<img width="1160" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/0bc07297-a5ca-4f6f-8de0-543a5c00513c">
