### ISSUE TITLE
一键包安装后vless-ws-tls上不去网，测试了好几台vps

### ISSUE THREAD

**Issue by cnfug** [fscarmen/sing-box#57]
INFO[0032] [3642008380 0ms] inbound/mixed[mixed-in]: inbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
INFO[0032] [3642008380 1ms] outbound/vless[proxy]: outbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
INFO[0032] [3642008380 1ms] outbound/vless[proxy]: outbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
ERROR[0033] [3360102226 1.7s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:55186: websocket: bad handshake: HTTP 520 520
INFO[0033] [3272498089 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:55191
INFO[0033] [3272498089 0ms] inbound/mixed[mixed-in]: [] inbound connection to 173.194.174.188:443
INFO[0033] [3272498089 1ms] outbound/vless[proxy]: outbound connection to 173.194.174.188:443
INFO[0033] [3272498089 1ms] outbound/vless[proxy]: outbound connection to 173.194.174.188:443
ERROR[0034] [3642008380 1.12s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:55189: websocket: bad handshake: HTTP 520 520
INFO[0034] [1771645140 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:55193
INFO[0034] [1771645140 0ms] inbound/mixed[mixed-in]: inbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
INFO[0034] [1771645140 1ms] outbound/vless[proxy]: outbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
INFO[0034] [1771645140 1ms] outbound/vless[proxy]: outbound connection to rr4---sn-i3b7knsl.googlevideo.com:443
ERROR[0034] [3272498089 1.16s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:55191: websocket: bad handshake: HTTP 520 520
ERROR[0036] [1771645140 2.34s] inbound/mixed[mixed-in]: process connection from 127.0.0.1:55193: websocket: bad handshake: HTTP 520 520

**Comment by fscarmen** [comment]
把域名ssl设为严格看看

**Comment by cnfug** [comment]
设置为FULL就可以了，谢谢
