### ISSUE TITLE
想问一下能不能在hysteria2搭建时添加证书啊，自签或者acme。还想问一下，没有证书的话安全性相比有的情况下会差吗？

### ISSUE THREAD

**Issue by ouojk** [fscarmen/sing-box#59]
想问一下能不能在hysteria2搭建时添加证书啊，自签或者acme。还想问一下，没有证书的话安全性相比有的情况下会差吗？

**Comment by fscarmen** [comment]
项目就是用自签的，没有 acme，暂时没有证据证明安全性有哪些具体差异。项目定位问题，后续也不会考虑加入 acme。

**Comment by ouojk** [comment]
好
