### ISSUE TITLE
sing-box无法启动

### ISSUE THREAD

**Issue by liujf916** [fscarmen/sing-box#60]
![image](https://github.com/fscarmen/sing-box/assets/158129502/06226322-efda-4699-8317-6f52d7cd8779)

_**root@ip-172-26-4-10:~# systemctl status sing-box.service**_
● sing-box.service - sing-box service
     Loaded: loaded (/etc/systemd/system/sing-box.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-03-04 10:00:53 UTC; 6s ago
       Docs: https://sing-box.sagernet.org
    Process: 11820 ExecStartPre=/usr/sbin/nginx -c /etc/sing-box/nginx.conf (code=exited, status=1/FAILURE)
        CPU: 5ms
_**root@ip-172-26-4-10:~# journalctl -xeu sing-box.service**_
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit sing-box.service has begun execution.
░░ 
░░ The job identifier is 7915.
Mar 04 10:02:15 ip-172-26-4-10 nginx[12671]: 2024/03/04 10:02:15 [emerg] 12671#12671: chown("/var/lib/nginx/body", 0) failed (1: Operation not permitted)
Mar 04 10:02:15 ip-172-26-4-10 systemd[1]: sing-box.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStartPre= process belonging to unit sing-box.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 04 10:02:15 ip-172-26-4-10 systemd[1]: sing-box.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit sing-box.service has entered the 'failed' state with result 'exit-code'.
Mar 04 10:02:15 ip-172-26-4-10 systemd[1]: Failed to start sing-box.service - sing-box service.
░░ Subject: A start job for unit sing-box.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit sing-box.service has finished with a failure.
░░ 
░░ The job identifier is 7915 and the job result is failed.
lines 4136-4164/4164 (END)

_**通过更改目录权限后仍然无法解决问题**_

**Comment by fscarmen** [comment]
更新了订阅功能 ，你重新安装一下试试。

**Comment by liujf916** [comment]
> 更新了订阅功能 ，你重新安装一下试试。

还是一样的情况，似乎是nginx的问题，更新反而不能用了

**Comment by fscarmen** [comment]
`systemctl start sing-box; sleep 2; ss -nltp` 看看服务有没有起来？

**Comment by liujf916** [comment]
> systemctl start sing-box; sleep 2; ss -nltp

![image](https://github.com/fscarmen/sing-box/assets/158129502/d4dc7bdb-8a19-4961-a33e-f181da2d47e1)
试了两台vps都是一样的情况，你应该也能复现。

**Comment by fscarmen** [comment]
我装了3台都行，你发个ssh到fscarmen@gmail.com
我排查下

**Comment by mirorr404** [comment]
我也是今天刚跟新的脚本 和楼上一样的问题  以为是系统问题  系统德班12 乌班图20 LTS

**Comment by mirorr404** [comment]
![photo_2024-03-04_19-10-23](https://github.com/fscarmen/sing-box/assets/78219911/efbf3716-e2a4-4335-9631-e18793f37139)

**Comment by liujf916** [comment]
> 我装了3台都行，你发个ssh到[fscarmen@gmail.com](mailto:fscarmen@gmail.com) 我排查下

已通过liujunfu916@outlook.com反馈

**Comment by mirorr404** [comment]
> > 我装了3台都行，你发个ssh到[fscarmen@gmail.com](mailto:fscarmen@gmail.com) 我排查下
> 
> 已通过[liujunfu916@outlook.com](mailto:liujunfu916@outlook.com)反馈
我和你出现一样的问题，等待作者修复。

**Comment by zdabing** [comment]
我也是楼上一样的问题 求修复

**Comment by fscarmen** [comment]
可能大家是直接升级，因为 systemd 文件变更了，大家这样处理
```
systemctl --disable now sing-box   ## 停服务
bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) -u  ## 卸载
bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)  ## 重装
```

<img width="1221" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/ed245d50-34bf-43bd-b19d-1eac683f9348">

**Comment by fscarmen** [comment]
> > 我装了3台都行，你发个ssh到[fscarmen@gmail.com](mailto:fscarmen@gmail.com) 我排查下
> 
> 已通过[liujunfu916@outlook.com](mailto:liujunfu916@outlook.com)反馈

上面的截图就是你的机器，我只安装了一个协议，你可以 使用  `sb -r` 增加

**Comment by ouojk** [comment]
> 可能大家是直接升级，因为 systemd 文件变更了，大家这样处理
> 
> ```
> systemctl --disable now sing-box   ## 停服务
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) -u  ## 卸载
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)  ## 重装
> ```
> 
> <img alt="image" width="1221" src="https://private-user-images.githubusercontent.com/62703343/309776309-ed245d50-34bf-43bd-b19d-1eac683f9348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjExNzksIm5iZiI6MTcwOTU2MDg3OSwicGF0aCI6Ii82MjcwMzM0My8zMDk3NzYzMDktZWQyNDVkNTAtMzRiZi00M2JkLWIxOWQtMWVhYzY4M2Y5MzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0MDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZDEyZDM4ODJmMDA3ZDI4ZWNkY2MyMzhhMGNhOGJiZWQ0YjYxMWZmZjI1M2U2ZjUwZGQwOWEwNDRjYzhlZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xejacvWDxfCfxHo8mcAoO4hoHpMB8ckIaqI7h4mbHEw">

这样还是行不通

**Comment by liujf916** [comment]
> 可能大家是直接升级，因为 systemd 文件变更了，大家这样处理
> 
> ```
> systemctl --disable now sing-box   ## 停服务
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) -u  ## 卸载
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)  ## 重装
> ```
> 
> <img alt="image" width="1221" src="https://private-user-images.githubusercontent.com/62703343/309776309-ed245d50-34bf-43bd-b19d-1eac683f9348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjI1MTIsIm5iZiI6MTcwOTU2MjIxMiwicGF0aCI6Ii82MjcwMzM0My8zMDk3NzYzMDktZWQyNDVkNTAtMzRiZi00M2JkLWIxOWQtMWVhYzY4M2Y5MzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0MjMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjZiNjJjNmU4OTA3ZDc1MThjYThjNmYwN2NjYjM4NTMwMmVmNzk1MTc3OTdjMjBjNGRjOTViZDMzNGM3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1NL9mRDqHDRh6hlbFO1qjz7MNnTBoB1Uct6JoQ58tq4">

我刚刚试了另一台vps还是不行

**Comment by fscarmen** [comment]
> 
> 这样还是行不通

但我测是通的啊。
![image](https://github.com/fscarmen/sing-box/assets/62703343/20f945e7-20cc-4733-b244-e51a73758fb5)

**Comment by liujf916** [comment]
> > 这样还是行不通
> 
> 但我测是通的啊。 ![image](https://private-user-images.githubusercontent.com/62703343/309791153-20f945e7-20cc-4733-b244-e51a73758fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjQwODgsIm5iZiI6MTcwOTU2Mzc4OCwicGF0aCI6Ii82MjcwMzM0My8zMDk3OTExNTMtMjBmOTQ1ZTctMjBjYy00NzMzLWIyNDQtZTUxYTczNzU4ZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZWFjODY0ZThhZmFlY2VlOGI1NWNhNDUyODU3NTNlY2E5YWQzYzVlY2I0YTRiYmYyOGU3YjRhNTVkMDNiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_dcAiFW3Dp2mAufQ4ojr0OJiyS3M6X61Wm-qF3ugmU)

就是按你的方法，一开始那个singbox无法启动的问题还是没有解决。

**Comment by fscarmen** [comment]
> > > 这样还是行不通
> > 
> > 
> > 但我测是通的啊。 ![image](https://private-user-images.githubusercontent.com/62703343/309791153-20f945e7-20cc-4733-b244-e51a73758fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjQwODgsIm5iZiI6MTcwOTU2Mzc4OCwicGF0aCI6Ii82MjcwMzM0My8zMDk3OTExNTMtMjBmOTQ1ZTctMjBjYy00NzMzLWIyNDQtZTUxYTczNzU4ZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZWFjODY0ZThhZmFlY2VlOGI1NWNhNDUyODU3NTNlY2E5YWQzYzVlY2I0YTRiYmYyOGU3YjRhNTVkMDNiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_dcAiFW3Dp2mAufQ4ojr0OJiyS3M6X61Wm-qF3ugmU)
> 
> 就是按你的方法，一开始那个singbox无法启动的问题还是没有解决。我用另外几台机器又不行了。

我给你弄那台也不行吗？我这里试是可以的，看油管的。

**Comment by liujf916** [comment]
> > > > 这样还是行不通
> > > 
> > > 
> > > 但我测是通的啊。 ![image](https://private-user-images.githubusercontent.com/62703343/309791153-20f945e7-20cc-4733-b244-e51a73758fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjQwODgsIm5iZiI6MTcwOTU2Mzc4OCwicGF0aCI6Ii82MjcwMzM0My8zMDk3OTExNTMtMjBmOTQ1ZTctMjBjYy00NzMzLWIyNDQtZTUxYTczNzU4ZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZWFjODY0ZThhZmFlY2VlOGI1NWNhNDUyODU3NTNlY2E5YWQzYzVlY2I0YTRiYmYyOGU3YjRhNTVkMDNiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_dcAiFW3Dp2mAufQ4ojr0OJiyS3M6X61Wm-qF3ugmU)
> > 
> > 
> > 就是按你的方法，一开始那个singbox无法启动的问题还是没有解决。我用另外几台机器又不行了。
> 
> 我给你弄那台也不行吗？我这里试是可以的，看油管的。

我那台可以，我另外几台也是相同的问题，然后用你说的那个方法不行。但是原来的版本没问题

**Comment by fscarmen** [comment]
> > > > > 这样还是行不通
> > > > 
> > > > 
> > > > 但我测是通的啊。 ![image](https://private-user-images.githubusercontent.com/62703343/309791153-20f945e7-20cc-4733-b244-e51a73758fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjQwODgsIm5iZiI6MTcwOTU2Mzc4OCwicGF0aCI6Ii82MjcwMzM0My8zMDk3OTExNTMtMjBmOTQ1ZTctMjBjYy00NzMzLWIyNDQtZTUxYTczNzU4ZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZWFjODY0ZThhZmFlY2VlOGI1NWNhNDUyODU3NTNlY2E5YWQzYzVlY2I0YTRiYmYyOGU3YjRhNTVkMDNiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_dcAiFW3Dp2mAufQ4ojr0OJiyS3M6X61Wm-qF3ugmU)
> > > 
> > > 
> > > 就是按你的方法，一开始那个singbox无法启动的问题还是没有解决。我用另外几台机器又不行了。
> > 
> > 
> > 我给你弄那台也不行吗？我这里试是可以的，看油管的。
> 
> 我那台可以，我另外几台也是相同的问题，然后用你说的那个方法不行。但是原来的版本没问题

你再把多台的ssh发我看看。

**Comment by Raid10Without1** [comment]
看起来这个问题的根源是创建nginx配置文件的时候出现了问题，导致nginx无法获取启动脚本然后导致了服务异常退出，手动注释掉文件内启动nginx的参数并手动创建sb.sh之后脚本可以正常运行除了订阅链接以外的所有内容

**Comment by fscarmen** [comment]
再多试一下这条指令
```
systemctl --disable now sing-box   ## 停服务
bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) -u  ## 卸载
ss -nltp | grep "$(cat /var/run/nginx.pid)" | tr ',' '\n' | awk -F '=' '/pid/{print $2}' | xargs kill -9  ## 清 nginx 进程
bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)  ## 重装
```

**Comment by mirorr404** [comment]
> 再多试一下这条指令
> 
> ```
> systemctl --disable now sing-box   ## 停服务
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh) -u  ## 卸载
> ss -nltp | grep "$(cat /var/run/nginx.pid)" | tr ',' '\n' | awk -F '=' '/pid/{print $2}' | xargs kill -9  ## 清 nginx 进程
> bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)  ## 重装
> ```

还是sing-box开启失败

**Comment by fscarmen** [comment]
明天再看了

**Comment by Ethan0x0000** [comment]
同遇到这个问题，我在安装其他sing-box脚本时也报错，似乎是不支持arm64架构导致根本装不上sing-box
![PixPin_2024-03-05_10-46-04](https://github.com/fscarmen/sing-box/assets/87119873/27241baa-04e6-4e6d-90ee-6c840c58f298)

**Comment by Ethan0x0000** [comment]
> 同遇到这个问题，我在安装其他sing-box脚本时也报错，似乎是不支持arm64架构导致根本装不上sing-box ![PixPin_2024-03-05_10-46-04](https://private-user-images.githubusercontent.com/87119873/309965413-27241baa-04e6-4e6d-90ee-6c840c58f298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDcxMzIsIm5iZiI6MTcwOTYwNjgzMiwicGF0aCI6Ii84NzExOTg3My8zMDk5NjU0MTMtMjcyNDFiYWEtMDRlNi00ZTZkLTkwZWUtNmM4NDBjNThmMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNzBiZGMyOGIwNGVhNTI1NzczMjRiMTFhYmQ2YWYwNGE3MDU2MDNlMGE0MDNkOTE2NmYwOWQ5NWUxZDhkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.76kDpmHCfzEp6KZs5FzGtEg_fu5BP6hf3GNSFbDfzmU)

我在另一台amd架构的VPS上也试了，亦然显示Sing-box open failed

**Comment by shidianxia** [comment]
用上一个版本的就没问题，似乎是和新增的订阅链接功能有关

**Comment by liujf916** [comment]
要不添加一个是否启用nginx订阅链接的选项吧，上一版本是完全正常能用的。

**Comment by fscarmen** [comment]
我先回滚了一个版本，等测试好再上订阅功能 。

**Comment by mirorr404** [comment]
> 我先回滚了一个版本，等测试好再上订阅功能 。

好的，其实我觉得没必要加订阅功能，大多数都是在nat鸡，128内存上跑。

**Comment by fscarmen** [comment]
搞掂了，大家可以再试试。

> 好的，其实我觉得没必要加订阅功能，大多数都是在nat鸡，128内存上跑。

nginx 占用不大的，3M 左右的。

**Comment by fscarmen** [comment]
<img width="1168" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/6f96f644-9385-4018-a16a-1158179563ab">

**Comment by liujf916** [comment]
刚刚测试正常了，感谢大佬

**Comment by fscarmen** [comment]
> 要不添加一个是否启用nginx订阅链接的选项吧，上一版本是完全正常能用的。

我是极度反感过量交互的，除非不得不问的！
