### ISSUE TITLE
sing-box客户端用不了,其它的客户端都没问题

### ISSUE THREAD

**Issue by helema** [fscarmen/sing-box#63]

**Comment by fscarmen** [comment]
https://sing-box.sagernet.org/zh/clients/

下载个最新版本看看。

**Comment by helema** [comment]
> https://sing-box.sagernet.org/zh/clients/
> 
> 下载个最新版本看看。

用的就是最新版的

**Comment by fscarmen** [comment]
用 /auto 的看看，如果仍然不行，建议到 sing-box 那里发发issue问下。
