### ISSUE TITLE
服务端自动生成的配置能否去掉 "sniff":true

### ISSUE THREAD

**Issue by betterdoitnow** [fscarmen/sing-box#64]
对于非域名的连接，会增加300ms的延迟。
另外，加上这个sniff，对于tuic/hy2的连接，surge的udp转发也会失败。

**Comment by fscarmen** [comment]
这个域名和协议嗅探用于防 dns 被 GFW 污染的
[【进阶•DNS代理篇】最完美的DNS解决方案？通过代理DNS请求获取正确的ip，杜绝DNS泄露和DNS污染，解决透明代理下fake-ip存在的问题，开启sniffing流量嗅探亦可解决污染问题](https://bulianglin.com/archives/dnsproxy.html)

**Comment by betterdoitnow** [comment]
谢谢解答！虽然觉得这个可能在客户端解决防止dns污染比较好，但是理解您的做法，谢谢
