### ISSUE TITLE
是否可以增加一个选项，是否默认开启warp(wireguard)访问openai的路由

### ISSUE THREAD

**Issue by betterdoitnow** [fscarmen/sing-box#65]
不少情况下，vps本身就是可以直连ChatGPT的，开启了warp之后反而不稳定，时不时失效。遇到过两次这个情况，默认配置warp路由失效了不能访问，把route改为direct之后，就正常了。

**Comment by betterdoitnow** [comment]
哈哈哈，那自然是极好的

**Comment by fscarmen** [comment]
处理了，没有增加交互了，默认使用 direct，检测是否是解锁区域，如果不是，改为 warp v4 和 v6 out了。下次你安装的时候看
`cat /etc/sing-box/conf/02_route.json`

**Comment by fscarmen** [comment]
现在只是简单的地区判断，如果还要检测ip是不是被ban，就要用curl命令，出于脚本尽量减少依赖的思路，全程用 wget ，没有安装curl

**Comment by mario-huang** [comment]
> 现在只是简单的地区判断，如果还要检测ip是不是被ban，就要用curl命令，出于脚本尽量减少依赖的思路，全程用 wget ，没有安装curl

大佬你好，我现在遇到的情况就是地区判断是解锁的，但是登录gpt提示我“disabled vps”，这就是被ban了吧，如何把warp开启呢
