### ISSUE TITLE
脚本功能很多，有些用不到，感觉有点臃肿

### ISSUE THREAD

**Issue by lleeopen** [fscarmen/sing-box#66]
你好，辛苦了，一直在用您的脚本，非常好，目前感觉功能越多依赖多有点臃肿，只想保留单纯的搭建节点功能，不需要其他多余的，脚本该怎么精简，还有选择使用正式版本或最新测试版本的功能

**Comment by fscarmen** [comment]
> 只想保留单纯的搭建节点功能，不需要其他多余的

你是指订阅和clash，sing-box客户端的整体输出这块吗？

订阅需要nginx和1个公网访问端口

sing-box输出需要 jq，这个一般系统是没安装的。至于为什么不用系统一般自带的 python3 -m json.tool，因为后者不支持emoji。

**Comment by lleeopen** [comment]
非常感谢您的解答，以下是我的个人想法，只需要sing-box搭建节点的功能和关键依赖，开bbr功能，sing-box正式版和测试版自由选择，订阅nginx对于vps搭建一个节点没什么用，还有vps硬件系统信息显示可以精简一些
![01](https://github.com/fscarmen/sing-box/assets/35162785/5d211f79-08de-403c-8319-c4e9db1562ee)
![02](https://github.com/fscarmen/sing-box/assets/35162785/9d94a1b7-3f0f-4cc7-853f-93b6cabdbd7d)

**Comment by fscarmen** [comment]
感谢意见，今天的版本将会有以下的改动，至于提到的最新版本和稳定版本，我还是不做了，理由是 sb 变动很大，两个版本的配置文件不一定通用的，如果不通用，要维护两套配置，处理不过来。若不需要订阅，不安装 nginx 和 qrencode ，仍然会输出各客户端的配置文件。

<img width="395" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/7d5b64c4-319b-4a98-98c8-76743fba7505">
<img width="773" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/b4985a4b-ba03-4d58-b287-b5ecc41d9a5d">
<img width="1158" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/9d4dbfb3-cfe6-48e1-b2f8-f61fa67bb302">

**Comment by lleeopen** [comment]
非常感谢，很人性化，辛苦了
