### ISSUE TITLE
sing-box订阅链接的配置会导致微信不停转圈收取中

### ISSUE THREAD

**Issue by shidianxia** [fscarmen/sing-box#67]
作者您好，

用最新版脚本生成的订阅链接，在iOS sing-box客户端上使用时，会出现微信一直收取中的状态，收不到最新的消息了，用的是Rule规则，其他的app和国内的网页都没有问题，我用其他机场的配置也没这个问题。不知道是什么原因。

**Comment by fscarmen** [comment]
你两个模板都试下呢

**Comment by shidianxia** [comment]
用/auto这个链接，微信的收取中要转 1分钟左右才能获取到，关闭sing-box就好了，/auto2 会直接报geoip db的错误。

**Comment by fscarmen** [comment]
第一个我这里没有发生这个问题啊，2的确是有问题是，转订阅网出来的模板，我看了下，是用很久的 geoip那堆东西，被世界弃用了，找到适合的替换他
