### ISSUE TITLE
建议增加个IP配置功能

### ISSUE THREAD

**Issue by zhanggaoxuan** [fscarmen/sing-box#69]
比如在有/64的IPv6的时候

可以设置默认就用某一个IP，等后面墙了，可以通过命令快速配置换一个，连接信息自动更新

这样的话基本上等于无限使用了

**Comment by fscarmen** [comment]
/64那很多ip，死一个，一个命令换下一个吗？

**Comment by zhanggaoxuan** [comment]
可以一个命令换下一个
如果做自动化的话，就比较麻烦了，比如用调用国内的ping的一些程序，设置定时任务，每1分钟ping一次，timeout直接换下一个。
/64的IPV6是2的64次方，总数为1844亿亿个，买个/64的机器够一辈子了

**Comment by fscarmen** [comment]
这个是个性化需求了，建议你做个ddns配合自动ping换ip脚本处理

**Comment by zhanggaoxuan** [comment]
可以做个简单的，就是手动，一个命令换下一个，然后自动更新所有的链接信息。

自动化麻烦。。

**Comment by fscarmen** [comment]
```
sed -i "s#旧IP#新IP#g" /etc/sing-box/conf/*
sb -n 
```

这样就会更新所有的信息了。

**Comment by zhanggaoxuan** [comment]
厉害，回头我拿ipv6的试试，IPv4的墙的太快。
下午装了一个，晚上IP就被墙了
