### ISSUE TITLE
alpine系统下无法显示订阅二维码

### ISSUE THREAD

**Issue by Gaslys** [fscarmen/sing-box#72]
脚本更新后debian、Ubuntu系统会出现报错：
/dev/fd/64: line 1784: qrencode: command not found
/dev/fd/64: line 1784: qrencode: command not found
/dev/fd/64: line 1894: qrencode: command not found
/dev/fd/64: line 1894: qrencode: command not found
应该是因为脚本没有自动安装qrencode依赖，手动安装后可以解决。
alpine下似乎不能安装qrencode依赖，后续会使用其他方式实现显示订阅二维码吗

**Comment by fscarmen** [comment]
https://github.com/fscarmen/sing-box/blob/02f88c5ad3b2a1055f4b3aaa29d1782d909b9ac4/sing-box.sh#L597

这里已经处理了，根据alpine系统，安装libqrencode-tools的

**Comment by fscarmen** [comment]
<img width="627" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/68e52587-d644-4ebd-8705-552aab05ee94">

**Comment by Gaslys** [comment]
是的，是在不需要订阅的情况下会出现，非常感谢
