### ISSUE TITLE
使用sb -v 升级核心有失败的情况

### ISSUE THREAD

**Issue by lleeopen** [fscarmen/sing-box#74]
![sb](https://github.com/fscarmen/sing-box/assets/35162785/cac34adb-6f72-4201-b971-fde0a135025f)

今天我有2台vps用sb -v 升级核心都是图片的情况，失败后节点连接失败，然后用sb -o 开启后正常 ，不知道我这情况是不是个例，我记得之前用sb -v 升级都是正常的。

脚本版本: v1.1.11 (2024.03.27)

**Comment by fscarmen** [comment]
这个我要下载 1.9.0-rc.2 ，再升级为 rc.3 试试才行，不过从 sb -o 成功来看，又好像不是大问题，说不定 rc.4 又会正常了，先等等，sb 升级是很不稳定的，多时各种bug

**Comment by fscarmen** [comment]
处理了，感谢反馈！
<img width="931" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/c4d3308d-9543-4afe-b0d2-146f71fb2732">

**Comment by lleeopen** [comment]
今天测试了一下，正常了，辛苦了

![ok](https://github.com/fscarmen/sing-box/assets/35162785/201f1a37-2ee2-4dea-be99-34ca6606b055)

**Comment by fscarmen** [comment]
不客气，有问题随时反馈
