### ISSUE TITLE
Request: Option to Add Custom SNI for Reality

### ISSUE THREAD

**Issue by SanujaNS** [fscarmen/sing-box#75]
Hello @fscarmen ,

Could you please consider implementing an option to add a custom SNI for Reality protocols? As far as I understand, Reality only requires user input for this configuration, while other protocols may need additional settings. Please correct me if I'm mistaken.

I would appreciate your feedback on this request. 
Thank you for your time and consideration.

**Comment by fscarmen** [comment]
I think that if you want to customize the TLS server in the "reality" option, it will definitely require an additional interaction, which will greatly affect the user experience.

If you haven't installed it yet, you can download the script and modify the website inside it:

```
wget https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh
sed -i "s/addons.mozilla.org/custom.sni.com/g" sing-box.sh
bash sing-box.sh
```

If you have already installed it, you can follow these steps:

```
sb -o  # close sing-box
sed -i "s/addons.mozilla.org/custom.sni.com/g" /etc/sing-box/conf/*    # modify sni server
sb -o  # open sing-box
sb -n  # list
```

**Comment by SanujaNS** [comment]
Thank you for your explanation and detailed instructions. I appreciate your guidance on how to add a custom SNI. The reason I opened this issue was to suggest implementing an option during the installation process that allows users to configure a custom SNI. As a user, I believe this option would enhance the overall experience.

I kindly request that you consider my suggestion and perhaps think about implementing this feature in the future. In the meantime, if it's okay with you, I'd like to keep this issue open so that other users who may need assistance with setting up a custom SNI can benefit from these instructions.

Thank you again for your time and attention.
