### ISSUE TITLE
Created symlink from /etc/systemd/system/multi-user.target.wants/sing-box.service to /etc/systemd/system/sing-box.service. /dev/fd/63: line 358: -c: command not found

### ISSUE THREAD

**Issue by 87Cloud** [fscarmen/sing-box#76]
Created symlink from /etc/systemd/system/multi-user.target.wants/sing-box.service to /etc/systemd/system/sing-box.service.
/dev/fd/63: line 358: -c: command not found

**Comment by fscarmen** [comment]
nginx没安装好，你手动安装看看
