### ISSUE TITLE
有没有人知道协议b组合的移动端客户端有没有支持的？

### ISSUE THREAD

**Issue by fxvbv** [fscarmen/sing-box#77]
试了好几个Windows和安卓客户端都无法使用，协议类型是组合b的。tcp-brush就算不支持理论上也能连接。目前只找到openwrt上的homeproxy和passwall系列的能使用。手动导入生成的各自配置文件也是显示握手失败，但是没显示报错的位置。

**Comment by fscarmen** [comment]
我这边测是可以的，你看看其他通不通，会不会IP已经被墙了？因为是直连协议

<img width="876" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/3b1dce64-aa3c-47a2-bd9a-d3e7b4310997">

<img width="1304" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/aa7d21ca-f39b-400d-bfb9-c22165cda6b2">

**Comment by fxvbv** [comment]
> 我的布拉格测是可以的，你看看其他通不通，会不会IP已经被墙了？因为是直连协议
> 
> <img alt="图像" width="876" src="https://private-user-images.githubusercontent.com/62703343/320198167-3b1dce64-aa3c-47a2-bd9a-d3e7b4310997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDkwOTQsIm5iZiI6MTcxMjQwODc5NCwicGF0aCI6Ii82MjcwMzM0My8zMjAxOTgxNjctM2IxZGNlNjQtYWEzYy00N2EyLWJkOWEtZDNlN2I0MzEwOTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEzMDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOWYxMjUxYTMyY2JjYTc3MGUyYzVlYmJlMTYxNTJlZjU0NGU1YWYzZDJmNzBlZDg4MmU2Y2I1YTM1ZGRkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5bzpmupKm-jUIro_C0k3FU7DTScpDuLsxT1mGxMvHd0"> <img alt="图像" width="1304" src="https://private-user-images.githubusercontent.com/62703343/320198187-aa7d21ca-f39b-400d-bfb9-c22165cda6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDkwOTQsIm5iZiI6MTcxMjQwODc5NCwicGF0aCI6Ii82MjcwMzM0My8zMjAxOTgxODctYWE3ZDIxY2EtZjM5Yi00MDBkLWJmYjktYzIyMTY1Y2RhNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEzMDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NjA3ZDMxY2U5ODYxMWJlZDY1NmM5N2E4Njc0NTM2MTFlNzMyN2JkYmQ5NzZkMzBkMWQ0OTFmNzBjZTdiM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKE4-PIlvu7mMxNbIuOuAtbdqo6XyrBpsCfEyH6Aigg">

谢谢，没有被封，是不是我没打开订阅端口导致的？

**Comment by fscarmen** [comment]
> 谢谢，没有被封，是不是我没打开订阅端口导致的？

这样连节点信息都读不出来，要手动输入的哦？
