### ISSUE TITLE
singbox启动失败

### ISSUE THREAD

**Issue by QAQ5555** [fscarmen/sing-box#78]
Sing-box：关闭
version:1.9.0-rc.5

请选择：2
ERROR:systemctl:the ExecStartPre control process
exited with error code
Sing-box 开启 失败

**Comment by fscarmen** [comment]
有没有安装 nginx？

**Comment by QAQ5555** [comment]
> 有没有安装 nginx？

重装多次和abc三个协议依次添加，终于正常了，原因未知

**Comment by fscarmen** [comment]
a(全部)和b(XTLS + reality) c(hysteria) 一起选的话，a会被忽略的。
