### ISSUE TITLE
1核512m内存的小鸡，用docker方式安装，u和内存都占用100%了，

### ISSUE THREAD

**Issue by QZQ-QSQ** [fscarmen/sing-box#79]
1核512m内存的小鸡，用docker方式安装，u和内存都占用100%了，
我想用docker logs -f sing-box查看日志都卡住了。
请大佬优化下，这个小鸡只做科学上网用。
以下是docker的配置
docker run -dit \
    --pull always \
    --name sing-box \
    -p 8800-8820:8800-8820/tcp \
    -p 8800-8820:8800-8820/udp \
    -e START_PORT=8800 \
    -e SERVER_IP=xx.xx.xx.xx \
    -e XTLS_REALITY=true \
    -e HYSTERIA2=true \
    -e TUIC=true \
    -e SHADOWTLS=false \
    -e SHADOWSOCKS=false \
    -e TROJAN=true \
    -e VMESS_WS=true \
    -e VLESS_WS=true \
    -e H2_REALITY=true \
    -e GRPC_REALITY=true \
    -e UUID=789B655B-BA24-7E81-B00B-xxxxxxxxxxxxxx \
    -e CDN=www.csgo.com \
    -e NODE_NAME=sing-box \
    -e ARGO_DOMAIN=sing-box.xxxxxxxxx.online \
    -e ARGO_AUTH=*************************************************************************** \
    fscarmen/sb

**Comment by fscarmen** [comment]
512MB内存应该能跑啊，不应该卡着啊，你在screen 下跑看如何

**Comment by fscarmen** [comment]
脚本版本: v1.2.0 (2024.04.12)

功能新增: 1. 增加 Cloudflare Argo Tunnel，让包括传输方式为ws在内的10个协议均不再需要自带域名; 2. Cloudflare Argo Tunnel 支持临时、Json 和 Token 方式，支持使用 [sb -r] 在线切换; 3. Cloudflare Argo Tunnel 开关为 [sb -a]，Sing-box 开关从 [sb -o] 更换为 [sb -s]; 4. 详细参考: https://github.com/fscarmen/sing-box

你试下这个 vps 版本的占用是否少点了，我估计 100MB 即可。

**Comment by QZQ-QSQ** [comment]
> 脚本版本: v1.2.0 (2024.04.12)
> 
> 功能新增: 1. 增加 Cloudflare Argo Tunnel，让包括传输方式为ws在内的10个协议均不再需要自带域名; 2. Cloudflare Argo Tunnel 支持临时、Json 和 Token 方式，支持使用 [sb -r] 在线切换; 3. Cloudflare Argo Tunnel 开关为 [sb -a]，Sing-box 开关从 [sb -o] 更换为 [sb -s]; 4. 详细参考: https://github.com/fscarmen/sing-box
> 
> 你试下这个 vps 版本的占用是否少点了，我估计 100MB 即可。

谢谢您！我重装了VPS的系统，用的debian12  x64，按照你的教程安装了docker，使用openclash，hysteria2，网速正常。估计是因为别的科学脚本，没卸载干净，有冲突，造成占用高。我完全不懂代码的，给你添麻烦了，不好意思。
       下图是看YouTube时的cpu和内存占用情况（只安装了这个科学上网docker）：
![捕获](https://github.com/fscarmen/sing-box/assets/13807219/b26c9d84-8912-4c98-837e-28a16caaa592)

**Comment by fscarmen** [comment]
你也可以用这个指令查看容器内存,CPU，网络等资源使用情况	`docker stats sing-box`

**Comment by QZQ-QSQ** [comment]
> 你也可以用这个指令查看容器内存,CPU，网络等资源使用情况 `docker stats sing-box`

谢谢！
占用情况
![捕获](https://github.com/fscarmen/sing-box/assets/13807219/e6c37940-219a-4d16-b7e6-df3f557ad705)

速度还是不错的。
![s](https://github.com/fscarmen/sing-box/assets/13807219/bac08dd5-9441-4976-a022-e693bf98b683)

**Comment by fscarmen** [comment]
很好，所以之前你说 512m 会爆我就是觉得奇怪，一般256已经能用了，有512已经可以的了。
