### ISSUE TITLE
reality协议可以增加vision流控吗

### ISSUE THREAD

**Issue by Idealisten** [fscarmen/sing-box#80]
不是说vision可以解决tls in tls 吗？大佬为啥没做进来呢？

**Comment by fscarmen** [comment]
为了使用多路复用，使用了 padding 替代  vision 流控

https://github.com/chika0801/sing-box-examples?tab=readme-ov-file

<img width="815" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/3cc0af35-b700-430b-8131-8ccad1b50932">
