### ISSUE TITLE
生成的 sing-box 订阅文件中 h2-reality 缺少 NODE_NAME 

### ISSUE THREAD

**Issue by asfork** [fscarmen/sing-box#85]
生成的 Sing-box 订阅文件如下：
```
    {
      "type": "urltest",
      "tag": "♻️ 自动选择",
      "outbounds": [
        "sing-box xtls-reality",
        "sing-box hysteria2",
        "sing-box tuic",
        "sing-box ShadowTLS",
        "sing-box shadowsocks",
        "sing-box trojan",
        "sing-box vmess-ws",
        "sing-box vless-ws-tls",
        " h2-reality",
        "sing-box grpc-reality"
      ],
      "url": "http://www.gstatic.com/generate_204",
      "interval": "5m",
      "tolerance": 50
    },
```

h2-reality 节点缺少 NODE_NAME 前缀

**Comment by fscarmen** [comment]
我印象中已经修复过了，我现在也复现不了。你是最近安装吗？如果不是，你试重新安装看看？

**Comment by asfork** [comment]
> 我印象中已经修复过了，我现在也复现不了。你是最近安装吗？如果不是，你试重新安装看看？

我使用的是 compose 版部署，compose 内容为README.md 中模板内容，多次重新部署后问题仍然复现。

**Comment by fscarmen** [comment]
的确有处变量名复制的时候没有改好，现已经处理并构建镜像了，你重新部署即可。
之前不能复现是因为不知道是 docker 版本那里，我还以为是 vps 的脚本。

<img width="336" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/43f41587-9d92-4b37-b83d-016e3dd98dff">

**Comment by asfork** [comment]
已解决，谢谢作者

**Comment by fscarmen** [comment]
这几天 vps 版本加了hysteria2的端口跳跃，但容器版本未想好如何处理，你有想法吗？

**Comment by asfork** [comment]
> 这几天 vps 版本加了hysteria2的端口跳跃，但容器版本未想好如何处理，你有想法吗？

抱歉，我没有使用过 hysteria2 协议，不太理解端口跳跃功能。但是理论上 Host 上脚本能实现的功能，容器中一样能。
合并 docker_init 和 sing-box.sh 脚本，在 sing-box.sh 中加上 if 判断是否存在环境变量，不存在则寻找 config 配置，再不存在才提示手动选择。在 compose 文件中提前分配所有需要的端口，或者直接 `network_mode: host` ，使用 host 网络模式。
这种方式可否实现你的需求，并避免重复开发的工作量？
