### ISSUE TITLE
Sing box 不能用 卸载重装了好多次重新订阅好多次还是这样

### ISSUE THREAD

**Issue by Ddiih** [fscarmen/sing-box#89]
![IMG_9692](https://github.com/fscarmen/sing-box/assets/169614530/14d1bc77-2c18-4b8f-af04-8b3384b2897f)

**Comment by fscarmen** [comment]
应该是原本的网络不能连接 github 下载 geoip.db 文件，我除了测试，几乎不使用 sing-box 客户端，建议先试试把上游路由器设置科学，在配置文件 /etc/sing-box/subscribe/sing-box-pc 文件处在这个文件前面加上 github 反代，比如 https://ghproxy.agrayman.gay/ ，如仍然不行就去 sing-box 那里发个 issue 问问。

**Comment by Ddiih** [comment]
> 应该是原本的网络不能连接 github 下载 geoip.db 文件，我除了测试，几乎不使用 sing-box 客户端，建议先试试把上游路由器设置科学，在配置文件 /etc/sing-box/subscribe/sing-box-pc 文件处在这个文件前面加上 github 反代，比如 https://ghproxy.agrayman.gay/ ，如仍然不行就去 sing-box 那里发个 issue 问问。


我这个是苹果手机的软件

**Comment by fscarmen** [comment]
你给个订阅我试试，fscarmen@gmail.com

**Comment by Ddiih** [comment]
https://github.com/fscarmen/sing-box/issues/89#issuecomment-2107059524
