### ISSUE TITLE
argo和sing-box能组合一下吗？

### ISSUE THREAD

**Issue by Pacio** [fscarmen/sing-box#9]
RTRTRT

**Comment by fscarmen** [comment]
Argo只能用在传输协议为ws，并不能用在直连。现在全家桶只有 vless + ws + tls  和 vmess + ws 符合，好像合在一起也意义不大，所以推荐用了 origin rules 来使用 cdn 了。

**Comment by fscarmen** [comment]
脚本版本: v1.2.0 (2024.04.12)

功能新增: 1. 增加 Cloudflare Argo Tunnel，让包括传输方式为ws在内的10个协议均不再需要自带域名; 2. Cloudflare Argo Tunnel 支持临时、Json 和 Token 方式，支持使用 [sb -r] 在线切换; 3. Cloudflare Argo Tunnel 开关为 [sb -a]，Sing-box 开关从 [sb -o] 更换为 [sb -s]; 4. 详细参考: https://github.com/fscarmen/sing-box
