### ISSUE TITLE
> 现在只是简单的地区判断，如果还要检测ip是不是被ban，就要用curl命令，出于脚本尽量减少依赖的思路，全程用 wget ，没有安装curl

### ISSUE THREAD

**Issue by mario-huang** [fscarmen/sing-box#90]
> 现在只是简单的地区判断，如果还要检测ip是不是被ban，就要用curl命令，出于脚本尽量减少依赖的思路，全程用 wget ，没有安装curl

大佬你好，我现在遇到的情况就是地区判断是解锁的，但是登录gpt提示我“disabled vps”，这就是被ban了吧，如何把warp开启呢

_Originally posted by @mario-huang in https://github.com/fscarmen/sing-box/issues/65#issuecomment-2111856812_

**Comment by fscarmen** [comment]
可能判断的方式更新了，你有用第三方的解锁脚本测过吗？哪个准确？

**Comment by mario-huang** [comment]
> 可能判断的方式更新了，你有用第三方的解锁脚本测过吗？哪个准确？

抱歉我是第一次接触warp这个东西，能告诉我有哪些测试脚本吗，我去测试。

**Comment by fscarmen** [comment]
你是指主机就是安装了本脚本，发现 gpt 访问不了？

**Comment by fscarmen** [comment]
也有这样的可能，vps 原生网络不解锁，同时用了 warp ipv6 依然不解锁的。

你可以谷歌一下脚本 https://www.google.com/search?q=%E6%9F%A5+gpt+%E8%A7%A3%E9%94%81&sca_esv=896ca77a4b5de4aa&source=hp&ei=nHhEZsaaAuPR2roPtvWp-A4&iflsig=AL9hbdgAAAAAZkSGrNlkXwgRey59oIfLqaqfWJEyLmcW&ved=0ahUKEwjG2OvKpI-GAxXjqFYBHbZ6Cu8Q4dUDCBU&uact=5&oq=%E6%9F%A5+gpt+%E8%A7%A3%E9%94%81&gs_lp=Egdnd3Mtd2l6Ig7mn6UgZ3B0IOino-mUgTIFECEYoAEyBRAhGKABSOIcUABYkxhwAHgAkAEAmAGEAaAB9gqqAQM1Lji4AQPIAQD4AQGYAgygAp0KwgIREC4YgAQYsQMY0QMYgwEYxwHCAg4QABiABBixAxiDARiKBcICCxAAGIAEGLEDGIMBwgIUEC4YgAQYsQMY0QMYgwEYxwEYigXCAhEQLhiABBixAxiDARjUAhiKBcICDhAuGIAEGLEDGNEDGMcBwgILEC4YgAQYsQMYgwHCAgsQLhiABBjRAxjHAcICBRAAGIAEwgILEC4YgAQYxwEYrwHCAggQABiABBixA8ICBRAuGIAEwgIOEC4YgAQYsQMYgwEYigXCAggQLhiABBixA8ICCxAAGIAEGLEDGIoFwgILEC4YgAQYsQMYigXCAgQQABgDwgIGEAAYBBgewgIEEAAYHsICBhAAGB4YD8ICCBAAGAQYHhgPwgIGEAAYBRgewgIIEAAYCBgeGA_CAggQABiABBiiBJgDAJIHBDIuMTCgB-hJ&sclient=gws-wiz#ip=1

**Comment by mario-huang** [comment]
> 你是指主机就是安装了本脚本，发现 gpt 访问不了？

嗯嗯是的。我选择只安装singbox+订阅，协议只有Hysteria2。客户端是sing-box.

**Comment by fscarmen** [comment]
1. `cat /etc/sing-box/conf/02_route.json`
2. 用上面搜索到的脚本，查查vps本身是否解锁
3. 再行判断如何处理

**Comment by mario-huang** [comment]
> 1. `cat /etc/sing-box/conf/02_route.json`
> 2. 用上面搜索到的脚本，查查vps本身是否解锁
> 3. 再行判断如何处理

cat /etc/sing-box/conf/02_route.json
```
{
    "route":{
        "rule_set":[
            {
                "tag":"geosite-openai",
                "type":"remote",
                "format":"binary",
                "url":"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-openai.srs"
            }
        ],
        "rules":[
            {
                "domain":"api.openai.com",
                "outbound":"direct"
            },
            {
                "rule_set":"geosite-openai",
                "outbound":"direct"
            }
        ]
    }
}
```

使用这个工具https://github.com/Netflixxp/chatGPT
得到结果
```
** Chat GPT ip可用性检测 by JCNF·那坨
** 提示 本工具测试结果仅供参考，请以实际使用为准
** 系统时间: Wed May 15 01:06:08 PM UTC 2024
 恭喜！本机IP:45.63.94.100 支持ChatGPT Yes (Region: US)
```

**Comment by mario-huang** [comment]
<img width="270" alt="Screenshot 2024-05-15 at 9 15 15 PM" src="https://github.com/fscarmen/sing-box/assets/6395323/f6153eb1-2563-4f8f-93dc-79a77cfdf62c">

**Comment by fscarmen** [comment]
检测脚本都说解锁哦，那脚本那里分流用 direct，即是用你原生的网络接口就没有错了，你试试用无痕模式看看，

**Comment by mario-huang** [comment]
> 检测脚本都说解锁哦，那脚本那里分流用 direct，即是用你原生的网络接口就没有错了，你试试用无痕模式看看，

我试了网页版，可以使用。然而同在这台电脑，app登录就是上面这个图。手机app也是一样，就很奇怪。

**Comment by fscarmen** [comment]
应该是app和应用会检测系统的vpn状态，我也是用网页版的，所以你在youtube 或者 谷歌找找你那个情况如何处理。

**Comment by mario-huang** [comment]
> 应该是app和应用会检测系统的vpn状态，我也是用网页版的，所以你在youtube 或者 谷歌找找你那个情况如何处理。

嗯嗯好的，谢谢～

**Comment by mario-huang** [comment]
> 应该是app和应用会检测系统的vpn状态，我也是用网页版的，所以你在youtube 或者 谷歌找找你那个情况如何处理。

又找了一个检测的
github.com/yonggekkk

它可以检测解锁客户端，好像也是装wrap。所以问题又回到了一开始的，因为大佬的一件脚本已经能使用wrap了，现在是需要手动开启它。

<img width="804" alt="Screenshot 2024-05-15 at 10 24 53 PM" src="https://github.com/fscarmen/sing-box/assets/6395323/584c8431-103a-4236-a0ac-cc9a80e66b15">

**Comment by fscarmen** [comment]
本脚本是把warp在sing-box里做链式代理连接的，宿主机没有安装 warp 的，我这里还有一个专门的一个warp脚本

**Comment by mario-huang** [comment]
我搞定了warp！感谢大佬指点！
