### ISSUE TITLE
无错误的情况下退出码为非0数字

### ISSUE THREAD

**Issue by MaleicAcid** [fscarmen/sing-box#94]
``` bash
root@hostname:~# sb -n
......
The script runs today: .....
root@hostname:~# echo $?
1
```

目前脚本成功执行后，是以1作为退出码的, 希望遵循Bash对错误码的约定: 
> "For the shell’s purposes, a command which exits with a zero exit status has succeeded"
see ref@https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

**Comment by fscarmen** [comment]
下次更新的时候处理

<img width="516" alt="image" src="https://github.com/fscarmen/sing-box/assets/62703343/13dc29fd-ae12-4443-a40c-d812dc0d1e9d">
