### ISSUE TITLE
question

### ISSUE THREAD

**Issue by c-2333** [fscarmen/sing-box#95]
The remote node can't use the imported singbox client, and wants to add a single node configurable domain name certificate, I hope I can add the function of self-signed domain name certificate.

**Comment by fscarmen** [comment]
Now using a self-signed certificate, the subscription generated locally on the vps is able to be used in the sing-box. Not quite sure what your needs are.
The subscript is `http://<ip:port>/uuid/` or  `https://<argo domain>/uuid/` .

**Comment by c-2333** [comment]
I hope that I can add a self-signed certificate for the domain name. I can use my own domain name certificate for the tls configuration. I also want to configure hysteria2 sni in the singbox. Why is the location where there should be an agency website left blank?

**Comment by c-2333** [comment]
What I mean is to add a domain name self-signed certificate, whether to use domain name or IP is configurable.

**Comment by fscarmen** [comment]
https://github.com/fscarmen/sing-box/issues/59

**Comment by fscarmen** [comment]
Here are three of a kind that can use acme certification for your needs:
1.  https://github.com/mack-a/v2ray-agent
2. https://github.com/FranzKafkaYu/sing-box-yes
3. https://github.com/alireza0/s-ui
4. https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality

**Comment by c-2333** [comment]
> #59

Okay, I would like to ask if the hysteria2 protocol built with the same IP cannot use the ChatGPT client, but the tcp transmission method used by vmess or vlewss can be used normally. Is there a solution to this?

**Comment by fscarmen** [comment]
Whether or not you can access chatGPT has nothing to do with vless/vmess/hysteria2 protocols, it's to do with whether or not the VPS ip is unlocked. For those that can't be unlocked by native IP, this project will use the built-in warp ipv6 , for access purposes.

**Comment by c-2333** [comment]
Sorry, using hysteria2 protocol is detected by GPT as a proxy, but using vmess protocol is normal，The ip used is the same.

**Comment by fscarmen** [comment]
I'm using the hysteria2 protocol on shadowrocket on ios and it works fine to access chatGPT. android i.e. I don't have a phone to test it on.
