### ISSUE TITLE
CF origin rules

### ISSUE THREAD

**Issue by lolisTop** [fscarmen/sing-box#96]
之前使用脚本 vless+ws+tls 設置 origin rules 可以正常使用；
這兩天報錯

`
2024/05/28 11:50:50 [Warning] [3277274183] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://visa.com/3bcd68dd-bbd3-4105-9681-1ffdc913f04a-vless):  > dial tcp 162.159.152.2:443: i/o timeout
`

**Comment by fscarmen** [comment]
检测下设置，如何什么都没改，试下换个优选看看

**Comment by fscarmen** [comment]
处理了吗？

**Comment by lolisTop** [comment]
@fscarmen 處理了, 優選網路 `visa.com` / `dash.cloudflare.com` 不太行, 默認的`cn.azhz.eu.org`可以.
