### ISSUE TITLE
在纯 IPV6 alpine VPS下午无法下载 sing-box 导致报错

### ISSUE THREAD

**Issue by crabpi** [fscarmen/sing-box#98]
bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/sing-box/main/sing-box.sh)

-----
 脚本版本: v1.2.4 (2024.05.09)
 功能新增: 添加 hysteria2 的跳跃端口，支持客户端: ShadowRocket / NekoBox / Clash
 系统信息:
	 当前操作系统: Alpine Linux v3.20
	 内核: 6.6.32-0-virt
	 处理器架构: amd64v3
	 虚拟化: kvm
	 IPv4:
	 IPv6: ****************  Scaleway
	 Sing-box: 未安装	 		
	 Argo: 未安装	 		
 	 Nginx: 未安装	 	
-----

报错内容

1.  安装 Sing-box + Argo + 订阅 ( 额外依赖: nginx )
 2.  安装 Sing-box + Argo ( 额外依赖: nginx )
 3.  安装 Sing-box + 订阅 ( 额外依赖: nginx )
 4.  安装 Sing-box
 5.  升级内核、安装BBR、DD脚本 (sb -b)
 6.  安装 ArgoX 脚本 (argo + xray) [https://github.com/fscarmen/argox]
 7.  安装 sba 脚本 (argo + sing-box) [https://github.com/fscarmen/sba]
 8.  安装 TCP brutal
 0.  退出

 请选择: 4

 (1/6) 多选需要安装协议(比如 hgbd)，协议的端口号次序与多选的排序有关:
 a. all (默认)
 b. XTLS + reality
 c. hysteria2
 d. tuic
 e. ShadowTLS
 f. shadowsocks
 g. trojan
 h. vmess + ws
 i. vless + ws + tls
 j. H2 + reality
 k. gRPC + reality

 请选择: i

 选择的协议及端口次序如下:
 1 . vless + ws + tls

 (2/6) 请输入开始的端口号，必须是 100 - 65520，需要连续1个空闲的端口 (默认为: 8881): 443

 (4/6) 请输入 VPS IP (默认为: 2001:bc8:1d90:3a4:dc00:ff:fe12:bd13):

 请输入 VLESS 域名: xxxxx.cdfsd.com

 1. cn.azhz.eu.org
 2. acjp.cloudflarest.link
 3. xn--b6gac.eu.org
 4. dash.cloudflare.com
 5. skk.moe
 6. visa.com

 请选择或者填入优选域名，默认为 cn.azhz.eu.org: 6

 (5/6) 请输入 UUID (默认为 5e00b357-99d9-400a-982a-760df92d8bd6):

 (6/6) 请输入节点名称 (默认为: scaleway-warsaw):

 下载 Sing-box 中，请稍等 ...
**/dev/fd/64: line 1247: /tmp/sing-box/sing-box: No such file or directory
cp: can't stat '/tmp/sing-box/sing-box': No such file or directory
ERROR:systemctl: sing-box.service: Exec command does not exist: (ExecStart) /etc/sing-box/sing-box
ERROR:systemctl: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR:systemctl: Oops, 1 executable paths were not found in the current environment. Refusing.
ERROR:systemctl: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

 Sing-box 开启 失败

**Comment by fscarmen** [comment]
按理用了github 反代的，或者你用个dns64先 
echo -e "nameserver 2a00:1098:2b::1\nnameserver 2a01:4f9:c010:3f02::1\nnameserver 2a01:4f8:c2c:123f::1\nnameserver 2a00:1098:2c::1" > /etc/resolv.conf

**Comment by crabpi** [comment]
还是不行
先用https://gitlab.com/fscarmen/warp 弄个 ipv4 的 ip 解决了
